// applications/angular-reference/src/pega/containers/Default.component.ts
import { Component } from "@angular/core";
import { PContainerComponent } from "@labb/angular-adapter";
import { Default } from "@labb/dx-engine";

@Component({
  selector: 'dx-default-container',
  template: `
      @for (child of container.children; track child.id) {
        <ng-template dxContainer [container]="child"></ng-template>
      }
  `,
  standalone: false
})
export class DefaultComponent extends PContainerComponent<Default> {
}

// applications/react-bank-of-ireland-investment/src/pega/containers/Default.tsx
import { PContainer } from '@labb/dx-engine';
import { GeneratePContainer } from '@labb/react-adapter';

export default function Default(props: { container: PContainer }) {
  return <>
    {props.container.children.map(child => (
      <GeneratePContainer key={child.id} container={child} />
    ))}
  </>
}
