// applications/react-hsbc/src/pega/containers/Checkbox.tsx
import { PContainer } from '@labb/dx-engine';
import HsbcCheckbox from '../../../design-system/hsbc-checkbox';
import HsbcFormElement from '../../../design-system/hsbc-form-element';

export default function DxCheckbox(props: {
  container: PContainer;
}): JSX.Element {
  if (props.container.config.readOnly) {
    return <><dt>{props.container.config.caption}</dt><dd>{props.container.config.value ? props.container.config.trueLabel : props.container.config.falseLabel}</dd></>;
  }
  return (
    <HsbcFormElement id={props.container.id}
      hint={props.container.config.helperText}
      error={props.container.config.validatemessage}>
      <HsbcCheckbox id={props.container.id}
        label={props.container.config.caption}
        value={props.container.config.value}
        onChange={v => {
          props.container.updateFieldValue(v);
          props.container.triggerFieldChange(v);
        }}
      />
    </HsbcFormElement>
  );
}

// applications/angular-athora/src/pega/containers/Checkbox.component.ts
import { Component } from '@angular/core';
import { ControlComponent } from '../control.component';

@Component({
  selector: 'dx-checkbox-control',
  template: `
    @if(container.config.readOnly) {
      <div class="dx-control">
        <mat-label>
          {{ container.config.label }}
        </mat-label>
        {{container.config.value ? container.config.trueLabel : container.config.falseLabel}}
      </div>
    } @else  {
      <mat-checkbox [formControl]="control">
        {{ container.config.caption }}
      </mat-checkbox>
      <mat-error *ngIf="container.config.validatemessage">{{container.config.validatemessage}}</mat-error>
      <br>
      <mat-hint *ngIf="container.config.helperText">{{container.config.helperText}}</mat-hint>
    }
  `,
  standalone: false
})
export class CheckboxComponent extends ControlComponent {
  public async updateValue(value: boolean): Promise<void> {
    await this.container.updateFieldValue(value);
    await this.container.triggerFieldChange(value);
  }

  public override toControlValue(val: boolean): boolean | null {
    return val;
  }

  public override toPegaValue(val: boolean | null): string {
    return !!val as unknown as string;
  }
}
