// applications/react-hsbc/src/pega/containers/Dropdown.tsx
import { PicklistProps } from '@labb/constellation-core-types';
import { PContainer } from '@labb/dx-engine';
import HsbcFormElement from 'applications/react-hsbc/design-system/hsbc-form-element';
import HsbcSelect from 'applications/react-hsbc/design-system/hsbc-select';

export default function DxDropdown(props: { container: PContainer<PicklistProps> }) {
  if (props.container.config.readOnly) {
    return <><dt>{props.container.config.label}</dt><dd>{props.container.config.value ?? '--'}</dd></>;
  }
  return <HsbcFormElement
    label={props.container.config.label}
    id={props.container.id}
    hint={props.container.config.helperText}
    error={props.container.config.validatemessage}
    >
    <HsbcSelect id={props.container.id}
      options={props.container.config.datasource}
      value={props.container.config.value}
      onChange={v => {
        props.container.updateFieldValue(v);
        props.container.triggerFieldChange(v);
      }} />
  </HsbcFormElement>
}

// applications/angular-athora/src/pega/containers/Dropdown.component.ts
import { Component } from '@angular/core';
import { ControlComponent } from '../control.component';
import { PicklistProps } from '@labb/constellation-core-types';

@Component({
  selector: 'dx-dropdown-control',
  template: `
    @if (container.config.readOnly) {
      <span>{{container.config.value}}</span>
    } @else {
      <div class="dx-control">
        <mat-label>
          {{ container.config.label }}
          <button type="button" mat-icon-button (click)="helperTextOpen = true" *ngIf="container.config.helperText"><mat-icon>info_outline</mat-icon></button>
        </mat-label>
        <mat-form-field>
          <mat-select [formControl]="control">
            <mat-option *ngFor="let option of container.config.datasource" [value]="option.key">
              {{option.value}}
            </mat-option>
          </mat-select>
          <mat-error *ngIf="container.config.validatemessage">{{container.config.validatemessage}}</mat-error>
        </mat-form-field>
      </div>
      <dx-hint *ngIf="container.config.helperText && helperTextOpen"
        (closed)="helperTextOpen = false"
        [hint]="container.config.helperText"></dx-hint>
    }
  `,
  standalone: false
})
export class DropdownComponent extends ControlComponent<string, PicklistProps> {
  public updateValue(val: string): void {
    this.container.updateFieldValue(val);
    this.container.triggerFieldChange(val);
  }

  public override toControlValue(val: string): string | null {
    return val;
  }

  public override toPegaValue(val: string | null): string {
    return val ?? '';
  }
}
