// applications/react-reference/src/pega/containers/Location.tsx
import { Location } from "@labb/dx-engine";
import { ChangeEvent, useEffect, useRef, useState } from "react";

export default function DxLocation(props: { container: Location }) {
    const map = useRef<HTMLDivElement | null>(null);
    const [suggestions, setSuggestions] = useState<string[]>([]);
    const [searchValue, setSearchValue] = useState<string>('');
    const { container } = props;

    useEffect(() => {
        (async () => {
            if (map.current) {
                await container.loadMap(map.current);
            }
        })();
    }, [map.current]);

    async function updateSearch(event: ChangeEvent) {
        const value = (event.target as HTMLInputElement)?.value;
        setSearchValue(value)
        setSuggestions(await container.getPlacePredictions(value));
    }

    async function select(event: ChangeEvent) {
        const value = (event.target as HTMLSelectElement).value;
        container.setLocation(value);
    }

    return <>
        {container.config.readOnly && <>
            <dt>{props.container.config.label}</dt><dd>{props.container.config.value ?? '--'}</dd>
        </>}
        {
            !container.config.readOnly && <>
                <label htmlFor={container.id}>
                    {container.config.label}
                    {container.config.required ? ' *' : ''}
                    {props.container.config.helperText && <span data-tooltip={props.container.config.helperText}>?</span>}
                </label>
                {props.container.config.validatemessage && <em>{props.container.config.validatemessage}</em>}
                <input type="text" id={container.id} value={searchValue} onChange={(event) => updateSearch(event)} />
                {suggestions.length > 0 &&
                    <select value={container.config.value} onChange={(event) => select(event)}>
                        <option value={''}>Select {container.config.label}...</option>
                        {suggestions.map(suggestion =>
                            <option key={suggestion} value={suggestion}>{suggestion}</option>
                        )}
                    </select>
                }
                <div ref={map} style={{ height: '25rem', display: container.config.value ? 'block' : 'none' }}></div>
            </>
        }
    </>
}

// applications/angular-athora/src/pega/containers/Location.component.ts
import { AfterViewInit, Component, ElementRef, ViewChild } from "@angular/core";
import { FormControl } from "@angular/forms";
import { PContainerComponent } from "@labb/angular-adapter";
import { Location } from "@labb/dx-engine";

@Component({
    selector: 'dx-location',
    template: `
    @if(container.config.readOnly) {
        <div class="dx-control">
          <mat-label>
            {{ container.config.label }}
          </mat-label>
          {{container.config.value}}
        </div>
    } @else  {
     <div class="dx-control">
        <mat-label>
            {{ container.config.label ?? '--'}}
        </mat-label>
        <mat-form-field [floatLabel]="'always'">
            <input
                matInput
                [value]="container.config.value"
                [formControl]="searchControl"
                (change)="updateSearch($event)"
            />
            @if(container.config.validatemessage) { <mat-error>{{container.config.validatemessage}}</mat-error> }
        </mat-form-field>
        </div>
        @if(suggestions.length > 0) {
            <div class="dx-control">
                <mat-label></mat-label>
                <mat-form-field [floatLabel]="'always'">
                    <mat-select [formControl]="selectControl">
                        @for(suggestion of suggestions; track suggestion) {
                            <mat-option [value]="suggestion">
                                {{suggestion}}
                            </mat-option>
                        }
                    </mat-select>
                </mat-form-field>
            </div>
        }
        <div #map [attr.style]="'height: 25rem; margin-bottom: 1.5rem; display: ' + (container.config.value ? 'block' : 'none')"></div>
    }
    `,
    standalone: false
})
export class LocationComponent extends PContainerComponent<Location> implements AfterViewInit {
    @ViewChild('map') map!: ElementRef;
    public searchControl = new FormControl('');
    public selectControl = new FormControl('');
    public suggestions: string[] = [];

    public async ngAfterViewInit(): Promise<void> {
        if (this.container.config.readOnly) return;
        await this.container.loadMap(this.map.nativeElement);
        this.selectControl.valueChanges.subscribe(() => {
            this.select(this.selectControl.value);
        })
    }

    public async updateSearch(event: Event) {
        this.suggestions = await this.container.getPlacePredictions((event.target as HTMLInputElement)?.value);
    }

    public async select(value: string | null) {
        if (value) {
            this.container.setLocation(value);
        }
    }
}
