// applications/angular-athora/src/pega/containers/CaseSummary.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';

@Component({
  selector: 'dx-case-summary',
  template: `
    <button role="button" (click)="showSummary = !showSummary">
      <h3>
        <span>Show Case Details</span>
      </h3>
    </button>
    @if (showSummary) {
      <div role="region">
        <div>
          @for (child of container.children; track child.id) {
            <ng-container dxContainer [container]="child"/>
          }
        </div>
      </div>
    }
  `,
  encapsulation: ViewEncapsulation.None,
  standalone: false
})
export class CaseSummaryComponent extends PContainerComponent {
  showSummary = false;
}

// applications/react-reference/src/pega/containers/CaseSummary.tsx
import { PContainer } from "@labb/dx-engine";
import { GeneratePContainer } from "@labb/react-adapter";
import { useState } from "react";

export default function DxCaseSummary(props: { container: PContainer }) {
    const [showSummary, setShowSummary] = useState(false);
    const { container } = props;
    return <>
        <a role="button" onClick={() => setShowSummary(!showSummary)}>
            <h3>
                <span>Show Case Details</span>
            </h3>
        </a>
        {showSummary &&
            <div role="region">
                {container.children.map(child => <GeneratePContainer key={child.id} container={child} />)}
            </div>
        }
    </>
}
