// applications/angular-reference/src/pega/containers/Location.component.ts
import { AfterViewInit, Component, ElementRef, ViewChild } from "@angular/core";
import { FormControl } from "@angular/forms";
import { PContainerComponent } from "@labb/angular-adapter";
import { Location } from "@labb/dx-engine";

@Component({
    selector: 'dx-location',
    template: `
         @if (container.config.readOnly) {
            <dt>{{ container.config.label }}</dt><dd>{{container.config.value ?? '--'}}</dd>
        } @else {
            <label [for]="container.id">
            {{ container.config.label }}{{ container.config.required ? ' *' : '' }}
            @if (container.config.helperText) {
                <span [attr.data-tooltip]="container.config.helperText">?</span>
            }
            </label>
            @if (container.config.validatemessage) {
                <em>{{ container.config.validatemessage }}</em>
            }
            <input type="text" [formControl]="searchControl" 
                (change)="updateSearch($event)"
                [id]="container.id">
        
            @if(suggestions.length > 0) {
                <select [formControl]="selectControl" (change)="select($event)">
                    <option value selected>Select {{container.config.label}}...</option>
                    @for(suggestion of suggestions; track suggestion) {
                        <option [value]="suggestion">{{suggestion}}</option>
                    }
                </select>
            }
            <div #map [attr.style]="'height: 25rem; margin-bottom: 1.5rem; display: ' + (container.config.value ? 'block' : 'none')"></div>
        }
    `,
    standalone: false
})
export class LocationComponent extends PContainerComponent<Location> implements AfterViewInit {
    @ViewChild('map') map!: ElementRef;
    public searchControl = new FormControl('');
    public selectControl = new FormControl('');
    public suggestions: string[] = [];

    public async ngAfterViewInit(): Promise<void> {
        await this.container.loadMap(this.map.nativeElement);
        if (this.container.config.value && !this.searchControl.value) {
            await this.prefill();
        }
        this.container.updates.subscribe(() => {
            if (this.container.config.value) {
                this.prefill();
            }
        });
    }

    private async prefill() {
        const event = { target: { value: this.container.config.value } } as any;
        this.searchControl.setValue(this.container.config.value);
        await this.updateSearch(event);
        this.selectControl.setValue(this.container.config.value);
        await this.select(event);
        await this.container.putMarker(this.container.config.value);
    }

    public async updateSearch(event: Event) {
        this.suggestions = await this.container.getPlacePredictions((event.target as HTMLInputElement)?.value);
    }

    public async select(event: Event) {
        await this.container.setLocation((event?.target as any).value);
    }
}

// applications/react-reference/src/pega/containers/Location.tsx
import { Location } from "@labb/dx-engine";
import { ChangeEvent, useEffect, useRef, useState } from "react";

export default function DxLocation(props: { container: Location }) {
    const map = useRef<HTMLDivElement | null>(null);
    const [suggestions, setSuggestions] = useState<string[]>([]);
    const [searchValue, setSearchValue] = useState<string>('');
    const { container } = props;

    useEffect(() => {
        (async () => {
            if (map.current) {
                await container.loadMap(map.current);
            }
        })();
    }, [map.current]);

    useEffect(() => {
        (async () => {
            if (container.config.value && !searchValue) {
                const event = { target: { value: container.config.value } } as any;
                await updateSearch(event);
                await select(event);
                await container.putMarker(container.config.value);
            }
        })();
    }, [container.config.value]);

    async function updateSearch(event: ChangeEvent) {
        const value = (event.target as HTMLInputElement)?.value;
        setSearchValue(value)
        setSuggestions(await container.getPlacePredictions(value));
    }

    async function select(event: ChangeEvent) {
        const value = (event.target as HTMLSelectElement).value;
        await container.setLocation(value);
    }

    return <>
        {container.config.readOnly && <>
            <dt>{props.container.config.label}</dt><dd>{props.container.config.value ?? '--'}</dd>
        </>}
        {
            !container.config.readOnly && <>
                <label htmlFor={container.id}>
                    {container.config.label}
                    {container.config.required ? ' *' : ''}
                    {props.container.config.helperText && <span data-tooltip={props.container.config.helperText}>?</span>}
                </label>
                {props.container.config.validatemessage && <em>{props.container.config.validatemessage}</em>}
                <input type="text" id={container.id} value={searchValue} onChange={(event) => updateSearch(event)} />
                {suggestions.length > 0 &&
                    <select value={container.config.value} onChange={(event) => select(event)}>
                        <option value={''}>Select {container.config.label}...</option>
                        {suggestions.map(suggestion =>
                            <option key={suggestion} value={suggestion}>{suggestion}</option>
                        )}
                    </select>
                }
                <div ref={map} style={{ height: '25rem', marginBottom: '1.5rem', display: container.config.value ? 'block' : 'none' }}></div>
            </>
        }
    </>
}
