// applications/angular-reference/src/pega/containers/FlowContainer.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';
import { ActionButton, Assignment } from '@labb/constellation-core-types';
import { FlowContainer } from '@labb/dx-engine';

@Component({
  selector: 'dx-flow-container',
  template: `
    <form>
      @for (message of container.config.caseMessages; track message) {
        <div>
          {{message}}
        </div>
      }
      @if (!container.hasAssignment()) {
          @for(assignment of todoAssignments; track assignment.ID) {
            <div>
              <div>{{assignment.processName}} > {{assignment.name}}</div>
              <div>Assigned to {{assignment.assigneeInfo?.name}}</div>
              <button type="button" (click)="openAssignment(assignment)">Go</button>
            </div>
          }
          @if(todoAssignments.length === 0) {
            <p>Thank you for your request. We will contact you as soon as possible.</p>
          }
      } @else {
        @if (container.navigation) {
          <nav>
            <ol>
              @for (step of container.navigation.steps; track step.ID) {
                <li>{{step.name}} [{{step.visited_status}}]</li>
              }
            </ol>
          </nav>
        }
        @for (message of container.config.pageMessages; track message.message) {
          <div>
            {{message.type}}: {{message.message}}
          </div>
        }
        <fieldset>
          <legend>
            <h2>
              {{container.getAssignmentName() || container.getActiveViewLabel()}}
            </h2>
          </legend>
          @for (child of container.children; track child.id) {
            <ng-container dxContainer [container]="child"/>
          }
        </fieldset>
        @if (container.actionButtons) {
          @for (button of container.actionButtons.secondary; track button.actionID) {
            <button
              type="button"
              [disabled]="loading"
              (click)="buttonClick(button)">
              {{ button.name }}
            </button>
          }
          @for (button of container.actionButtons.main; track button.actionID) {
            <button
              type="button"
              [disabled]="loading"
              (click)="buttonClick(button)">
              {{ button.name }}
            </button>
          }
        }
        <div>{{ errorMessage }}</div>
      }
    </form>
  `,
  standalone: false
})
export class FlowContainerComponent extends PContainerComponent<FlowContainer> implements OnInit, OnDestroy {
  public todoAssignments: Assignment[] = [];
  public errorMessage?: string;
  public loading = false;

  public override ngOnInit(): void {
    super.ngOnInit();
    this.updateAssignments();
    this.container.updates.subscribe(() => {
      this.updateAssignments();
    });
  }

  public openAssignment(assignment: Assignment) {
    this.container.openAssignment(assignment);
  }

  private updateAssignments(): void {
    this.todoAssignments = this.container.getTodoAssignments();
  }

  public async buttonClick(button: ActionButton): Promise<void> {
    try {
      delete this.errorMessage;
      this.loading = true;
      await this.container.buttonClick(button);
    } catch (e) {
      const error = e as { message: string; type: string };
      this.errorMessage = error?.message || error?.type || 'Error';
    }
    this.loading = false;
  }

}

// applications/react-virgin-media/src/pega/containers/FlowContainer.tsx
import { ActionButton, Assignment } from '@labb/constellation-core-types';
import { FlowContainer } from '@labb/dx-engine';
import { GeneratePContainer } from '@labb/react-adapter';
import { useEffect, useState } from 'react';

export default function DxFlowContainer(props: { container: FlowContainer }) {
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [todoAssignments, setTodoAssignments] = useState<Assignment[]>([]);

  useEffect(() => {
    updateAssignments();
    props.container.updates.subscribe(() => {
      updateAssignments();
    });
  }, []);

  function openAssignment(assignment: Assignment) {
    props.container.openAssignment(assignment);
  }

  function updateAssignments(): void {
    setTodoAssignments(props.container.getTodoAssignments());
  }

  function handleActionError(e: Error) {
    console.error(e);
    setErrorMessage(e.message || 'Error');
  }

  function buttonClick(button: ActionButton) {
    setErrorMessage(null);
    props.container.buttonClick(button).catch(handleActionError)
  }

  return <>
    <div className="container-fluid">
      {props.container.config.caseMessages?.map(message =>
        <div key={message}>
          {message}
        </div>
      )}
      {!props.container.hasAssignment() && <>
        {todoAssignments.map(assignment =>
          <div key={assignment.ID}>
            <div>{assignment.processName} {'>'} {assignment.name}</div>
            <div>Assigned to {assignment.assigneeInfo?.name}</div>
            <button type="button" onClick={() => openAssignment(assignment)}>Go</button>
          </div>
        )}
        {todoAssignments.length === 0 && <p>Thank you for your request. We will contact you as soon as possible.</p>}
      </>}
      {props.container.hasAssignment() && <form className="ace-form">
        <ul>
          {props.container.navigation?.steps.map((step, i) => (
            <li key={`first_${i}`}>
              {step.name} ({step.ID}: {step.visited_status})
            </li>
          ))}
        </ul>
        <fieldset>
          <legend>
            <h2>
              {props.container.getActiveViewLabel() ||
                props.container.getAssignmentName()}
            </h2>
          </legend>
          {props.container.children.map((child) => (
            <GeneratePContainer key={child.id} container={child} />
          ))}
        </fieldset>
        {props.container.actionButtons && (
          <>
            <div className="primary-button variantConfigurable component dyn-form-primary-cta-default initialized">
              <div className="form-group dyn-form-field initialized">
                <div className="btn-group">
                  {props.container.actionButtons.secondary.map((button, idx) => (
                    <button
                      key={`secondary_${idx}`}
                      type="button"
                      className="btn btn-secondary button-secondary-default"
                      onClick={() => buttonClick(button)}
                    >
                      <div className="button-default-text">
                        <p>{button.name}</p>

                      </div>
                      <div className="button-spinner-active-text hidden">
                        <div className="button-spinner-inner">
                          <i className="fa fa-circle-o-notch fa-spin"></i>

                        </div>
                      </div>
                    </button>
                  ))}
                  {props.container.actionButtons.main.map((button, idx) => (
                    <button
                      key={`main_${idx}`}
                      type="button"
                      className="btn btn-primary button-primary-default"
                      onClick={() => buttonClick(button)}
                    >
                      <div className="button-default-text">
                        <p>{button.name}</p>

                      </div>
                      <div className="button-spinner-active-text hidden">
                        <div className="button-spinner-inner">
                          <i className="fa fa-circle-o-notch fa-spin"></i>
                        </div>
                      </div>
                    </button>
                  ))}
                </div>
              </div>
            </div>
          </>
        )}
        {errorMessage && <div>{errorMessage}</div>}
      </form>}
    </div>
  </>
}
