// applications/vue-hca/src/app/container-mapping/SimpleTableManual.vue
<script setup lang="ts">
import { SimpleTableManual } from '@labb/dx-engine';
import { DxContainer } from '@labb/vue-adapter';

defineProps<{
    container: SimpleTableManual;
}>();

</script>

<template>
    <h3 v-if="container.config.label">{{container.config.label}}</h3>
      <table v-if="container.readOnlyMode">
        <thead>
            <th v-for="col in container.processedFields" :key="col.config.name">{{col.config.label}}</th>
        </thead>
        <tbody>
            <tr v-for="row in container.rowData" :key="row.id">
                <td v-for="col in container.processedFields" :key="col.config.name" v-html="row[col.config.name] || '---'"></td>
            </tr>
        </tbody>
      </table>
      <table v-if="container.editableMode">
        <thead>
            <th v-for="col in container.fieldDefs" :key="col.name">{{col.label}}</th>
        </thead>
        <tbody>
            <tr v-for="(row, index) in container.elementsData" :key="index">
                <td v-for="col of row" :key="col.id">
                    <DxContainer :container="col" />
                </td>
            </tr>
        </tbody>
      </table>
</template>

// applications/react-virgin-media/src/pega/containers/SimpleTableManual.tsx
import { SimpleTableManual } from '@labb/dx-engine';
import { GeneratePContainer } from '@labb/react-adapter';

export default function DxSimpleTableManual(props: { container: SimpleTableManual }) {
  const { container } = props;
  return <>
    {container.config.label && <h3>{container.config.label}</h3>}
    {container.readOnlyMode &&
      <table>
        <thead>
          <tr>
            {container.processedFields.map(col => <th key={col.config.name}>{col.config.name}</th>)}
          </tr>
        </thead>
        <tbody>
          {container.rowData.map((row, index) => <tr key={index}>
            {
              container.processedFields.map(col =>
                <td key={col.config.name} dangerouslySetInnerHTML={{ __html: row[col.config.name] || '---' }}></td>
              )
            }
          </tr>)}
        </tbody>
      </table>
    }
    {container.editableMode &&
      <table>
        <thead>
          <tr>
            {container.fieldDefs.map(col => <th key={col.name}>{col.label}</th>)}
          </tr>
        </thead>
        <tbody>
          {container.elementsData.map((row, rowIndex) =>
            <tr key={rowIndex}>
              {row.map((col, colIndex) => <td key={colIndex}><GeneratePContainer container={col} /></td>)}
            </tr>
          )}
        </tbody>
      </table>
    }
  </>
}
