// applications/angular-reference/src/pega/containers/Attachment.component.ts
import { AfterViewInit, Component, ElementRef, ViewChild } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';
import { Attachment, FileStatus } from '@labb/dx-engine';

@Component({
  selector: 'dx-attachment-control',
  template: `
    <label>
      {{ container.config.label }}{{ container.config.required ? ' *' : '' }}
      @if (allowMultiple || !container.files.length) {
        <input #fileInput type="file" 
          (change)="upload($event)" 
          [multiple]="allowMultiple"
        />
      }
      {{ container.config.helperText }}
      {{ container.config.validatemessage }}
      {{ container.config.extensions }}
    </label>
    @if (container.files.length) {
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Size</th>
            <th>Type</th>
            <th>Progress</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          @for (file of container.files; track file.id) {
            <tr>
              <td>{{file.name}}</td>
              <td>{{container.formatBytes(file.size!)}}</td>
              <td>{{file.type}}</td>
              <td>{{file.progress}}</td>
              <td>
                <button type="button" (click)="remove(file)">Delete</button>
                @if (file.type.startsWith('image')) { <button type="button" (click)="preview(file)">Preview</button> }
              </td>
            </tr>
          }
        </tbody>
      </table>
    }
    <dialog #dialogRef>
      <button type="button" (click)="dialog.nativeElement.close()">Close</button>
      <img width="100%" [src]="downloadedImage" />
    </dialog>
  `,
  standalone: false
})
export class AttachmentComponent extends PContainerComponent<Attachment> {
  @ViewChild('dialogRef') dialog!: ElementRef<HTMLDialogElement>;
  public downloadedImage?: string;

  public get allowMultiple(): boolean {
    return this.container.config.allowMultiple === 'true';
  }

  public async preview(file: FileStatus) {
    if (file.linked) {
      this.downloadedImage = 'data:image/png;base64,' + await this.container.downloadFile(file.id);
    } else {
      this.downloadedImage = file.src;
    }
    this.dialog.nativeElement.showModal();
  }

  public async upload(e: Event): Promise<void> {
    await this.container.uploadFile(e);
  }

  public async remove(file: FileStatus): Promise<void> {
    await this.container.removeFile(file.id);
  }

  public async download(file: FileStatus): Promise<void> {
    this.downloadedImage = await this.container.downloadFile(file.id);
  }
}

// applications/react-fbto/src/pega/containers/Attachment.tsx
import { Attachment, FileStatus } from '@labb/dx-engine';
import { useRef, useState } from 'react';
import TextInput from '../../design-system/fbto-text-input';

export default function DxAttachment(props: {
  container: Attachment;
}): JSX.Element {
  const { container } = props;
  const [downloadedImage, setDownloadedImage] = useState<string | undefined>();
  const dialog = useRef<HTMLDialogElement>(null);
  async function preview(file: FileStatus) {
    if (file.linked) {
      setDownloadedImage('data:image/png;base64,' + await container.downloadFile(file.id))
    } else {
      setDownloadedImage(file.src);
    }
    dialog.current?.showModal();
  }
  return <>
    <TextInput id={props.container.id}
      errorMessage={props.container.config.validatemessage}
      helperMessage={props.container.config.helperText}
      placeholder={props.container.config.placeholder}
      type="file"
      multiple={props.container.config.allowMultiple === 'true'}
      label={props.container.config.label}
      required={props.container.config.required}
      onChange={async (e) => {
        await container.uploadFile(e as unknown as Event);
      }}
    />
    {
      container.files.length > 0 &&
      <table>
        <tbody>
          {container.files.map(file =>
            <tr key={file.id}>
              <td>{file.name}</td>
              <td>{container.formatBytes(file.size!)}</td>
              <td>{file.type}</td>
              <td>{file.progress}%</td>
              <td>
                <button type="button" onClick={() => container.removeFile(file.id)}>Delete</button>
                {file.type.startsWith('image') && <button type="button" onClick={async () => preview(file)}>Preview</button>}
              </td>
            </tr>
          )}
        </tbody>
      </table>
    }
    <dialog ref={dialog}>
      <button type="button" onClick={async () => dialog.current?.close()}>Close</button>
      <img width="100%" src={downloadedImage} />
    </dialog>
  </>;
}
