// applications/vue-reference/src/app/container-mapping/RadioButtons.vue
<script setup lang="ts">
import { PContainer } from '@labb/dx-engine';

defineProps<{
    container: PContainer;
}>();

function getValue(target: EventTarget | null): string {
    return (target as HTMLInputElement).value;
}
</script>

<template>
    <fieldset>
        <legend>
            {{ container.config.label }}{{
                container.config.required ? ' *' : '' }}
        </legend>
        <template
            v-for="option in container.config.datasource"
            :key="option.key">
            <input type="radio"
            @change="container.updateFieldValue(getValue($event.target))"
            @blur="container.triggerFieldChange(getValue($event.target))"
            :id="container.id"
            :checked="container.config.value === option.key"
            :name="container.config.label"
            :value="option.value" />
            <label :for="container.id">{{ option.value }}</label>
            <br/>
        </template>
        {{ container.config.helperText }}
        {{ container.config.validatemessages }}
    </fieldset>
</template>

// applications/react-fbto/src/pega/containers/RadioButtons.tsx
import { PContainer } from '@labb/dx-engine';

export default function RadioButtons(props: { container: PContainer }) {
  function getValue(target: EventTarget | null): string {
    return (target as HTMLInputElement).value;
  }

  return (
    <fieldset>
      <legend>
        {props.container.config.label}
        {props.container.config.required ? ' *' : ''}
      </legend>
      {props.container.config.datasource.map(
        (option: { key: string; value: string }) => (
          <label key={option.key}>
            <input
              type="radio"
              onChange={(e) =>
                props.container.updateFieldValue(getValue(e.target))
              }
              onBlur={(e) =>
                props.container.triggerFieldChange(getValue(e.target))
              }
              checked={props.container.config.value === option.key}
              name={props.container.id}
              id={`${props.container.id}.${option.key}`}
              value={option.key}
              readOnly={props.container.config.readOnly}
              disabled={props.container.config.readOnly}
            />{' '}
            {option.value}
          </label>
        )
      )}
      {props.container.config.helperText}
      {props.container.config.validatemessage}
    </fieldset>
  );
}
