// applications/angular-carbon/src/pega/controls/RadioButtons.component.ts
import { Component } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';
import { RadioChange } from 'carbon-components-angular';

@Component({
  selector: 'dx-radio-buttons-control',
  template: `
  <ibm-label
    [invalid]="!!container.config.validatemessage"
    [invalidText]="container.config.validatemessage"
    [helperText]="container.config.helperText">
    {{container.config.label}}
    <ibm-radio-group
      [disabled]="container.config.readOnly"
      (change)="onChange($event)">
      <ibm-radio *ngFor="let option of container.config.datasource"
        [value]="option.key"
        [checked]="container.config.value === option.key">
          {{option.value}}
      </ibm-radio>
    </ibm-radio-group>
  </ibm-label>`,
})
export class RadioButtonsComponent extends PContainerComponent {
  public onChange(val: RadioChange): void {
    this.container.updateFieldValue(val.value);
    this.container.triggerFieldChange(val.value);
  }
}

// applications/react-fbto/src/pega/containers/RadioButtons.tsx
import { PContainer } from '@labb/dx-engine';

export default function RadioButtons(props: { container: PContainer }) {
  function getValue(target: EventTarget | null): string {
    return (target as HTMLInputElement).value;
  }

  return (
    <fieldset>
      <legend>
        {props.container.config.label}
        {props.container.config.required ? ' *' : ''}
      </legend>
      {props.container.config.datasource.map(
        (option: { key: string; value: string }) => (
          <label key={option.key}>
            <input
              type="radio"
              onChange={(e) =>
                props.container.updateFieldValue(getValue(e.target))
              }
              onBlur={(e) =>
                props.container.triggerFieldChange(getValue(e.target))
              }
              checked={props.container.config.value === option.key}
              name={props.container.id}
              id={`${props.container.id}.${option.key}`}
              value={option.key}
              readOnly={props.container.config.readOnly}
              disabled={props.container.config.readOnly}
            />{' '}
            {option.value}
          </label>
        )
      )}
      {props.container.config.helperText}
      {props.container.config.validatemessage}
    </fieldset>
  );
}
