// applications/react-virgin-media/src/pega/containers/DefaultForm.tsx
import { PContainer } from '@labb/dx-engine';
import { GeneratePContainer } from '@labb/react-adapter';

export default function DefaultForm(props: { container: PContainer }) {
  const { container } = props;
  function getClassName() {
    let divClass = 'one-column';
    switch (container.config.NumCols ?? '1') {
      case '1':
        divClass = 'one-column';
        break;
      case '2':
        divClass = 'two-column';
        break;
      case '3':
        divClass = 'three-column';
        break;
      default:
        divClass = 'one-column';
        break;
    }
    if (container.children.length <= 2) {
      divClass = 'one-column';
    }
    return divClass
  }

  return <div className={getClassName()}>
    {props.container.children.map((child) => (
      <GeneratePContainer container={child} key={child.id} />
    ))}
  </div>
}

// applications/angular-reference/src/pega/containers/DefaultForm.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';

@Component({
  selector: 'dx-default-form-template',
  template: `
    <div [ngClass]="divClass">
      @for (child of container.children; track child.id) {
        <ng-container dxContainer [container]="child"/>
      }
    </div>
  `,
  styles: [
    `
      .one-column {
        display: grid;
        grid-template-columns: repeat(1, 1fr);
        gap: calc(1rem);
      }
    `,
    `
      .two-column {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: calc(1rem);
      }
    `,
    `
      .three-column {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: calc(1rem);
      }
    `,
  ],
  encapsulation: ViewEncapsulation.None,
  standalone: false
})
export class DefaultFormComponent
  extends PContainerComponent
  implements OnInit {
  public divClass = 'one-column';

  public override ngOnInit(): void {
    super.ngOnInit();
    switch (this.container.config.NumCols ?? '1') {
      case '1':
        this.divClass = 'one-column';
        break;
      case '2':
        this.divClass = 'two-column';
        break;
      case '3':
        this.divClass = 'three-column';
        break;
      default:
        this.divClass = 'one-column';
        break;
    }
    if (this.container.children.length <= 2) {
      this.divClass = 'one-column';
    }
  }
}
