// applications/react-bank-of-ireland/src/pega/containers/ListView.tsx
import { ListView } from '@labb/dx-engine';

export default function DxListView(props: { container: ListView }) {
  const { container } = props;
  return <>
    <label htmlFor={props.container.id}>
      {props.container.config.label}
      {props.container.config.required ? ' *' : ''}
      {props.container.config.helperText && <span data-tooltip={props.container.config.helperText}>?</span>}
    </label>
    {props.container.config.validatemessage && <em>{props.container.config.validatemessage}</em>}
    <table>
      <thead>
        <tr>
          {(container.singleSelectionMode || container.multiSelectionMode) && <th>Select</th>}
          {container.fields.map(col => <th key={col.config.label}>{col.config.label}</th>)}
        </tr>
      </thead>
      <tbody>
        {container.updatedRefList.map(row =>
          <tr key={row.id}>
            {container.singleSelectionMode &&
              <td>
                <input type="radio"
                  name={container.id}
                  value={row[container.rowID]}
                  checked={row[container.rowID] === container.config.value}
                  onChange={() => container.selectRow(row)} />
              </td>
            }
            {container.multiSelectionMode &&
              <td>
                <input type="checkbox"
                  name={container.id}
                  value={row[container.rowID]}
                  checked={row[container.rowID] === container.config.value}
                  onChange={e => container.selectRow(row, e.target.checked)} />
              </td>
            }
            {container.fields.map(col => container.showButton(col.config.name, col) ?
              <td key={col.config.name}>
                <a type="button" href="#"
                  onClick={(e) => {e.preventDefault(); container.listViewClick(col.config, row)}}
                  dangerouslySetInnerHTML={{ __html: row[col.config.name] || '---' }}/>
              </td> :
              <td key={col.config.name} dangerouslySetInnerHTML={{ __html: row[col.config.name] || '---' }}></td>
            )}
          </tr>
        )}
      </tbody>
    </table>
  </>
}

// applications/angular-reference/src/pega/containers/ListView.component.ts
import { Component, OnInit } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';
import { ListView } from '@labb/dx-engine';

@Component({
  selector: 'dx-list-view-container',
  template: `
    <label [for]="container.id">
      {{ container.label }}{{ container.config.required ? ' *' : '' }}
      @if (container.config.helperText) {
        <span [attr.data-tooltip]="container.config.helperText">?</span>
      }
    </label>
    @if (container.config.validatemessage) {
      <em>{{ container.config.validatemessage }}</em>
    }
    <table>
      <thead>
        <tr>
          @if(container.singleSelectionMode || container.multiSelectionMode) {
            <th></th>
          }
          @for(col of container.fields; track col.config.name) {
            <th>{{col.config.label}}</th>
          }
        </tr>
      </thead>
      <tbody>
        @for(row of container.updatedRefList; track row.id) {
          <tr>
            @if(container.singleSelectionMode) {
              <td>
                <input type="radio" 
                  [name]="container.id" 
                  [value]="row[container.rowID]" 
                  [checked]="row[container.rowID] === container.config.value" 
                  (change)="selectRow(row)"/>
              </td>
            }
            @if(container.multiSelectionMode) {
              <td>
                <input type="checkbox"
                  [name]="container.id"
                  [value]="row[container.rowID]"
                  [checked]="row[container.rowID] === container.config.value"
                  (change)="selectRow(row, $event)"/>
              </td>
            }
            @for(col of container.fields; track col.config.name) {
              @if(container.showButton(col.config.name, col)) {
                  <td>
                      <a (click)="container.listViewClick(col.config, row)"
                          [innerHTML]="row[col.config.name] || '---'"></a>
                  </td>
              } @else {
                  <td [innerHTML]="row[col.config.name] || '---'"></td>
              }
            }
          </tr>
        }
      </tbody>
    </table>
  `,
  standalone: false
})
export class ListViewComponent extends PContainerComponent<ListView> implements OnInit {
  public selectRow(row: any, event?: Event) {
    this.container.selectRow(row, event && (event.target as HTMLInputElement).checked);
  }
}
