// applications/angular-reference/src/pega/containers/ActionableButton.component.ts
import { Component } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';

@Component({
  selector: 'dx-actionable-button-container',
  template: `
    <div>
      <button type="button" (click)="performAction()">{{container.config.label}}</button>
    </div>
  `,
})
export class ActionableButtonComponent extends PContainerComponent {
  public performAction() {
    this.container.pconnect
      .getActionsApi()
      .openLocalAction(this.container.config.localAction, {
        caseID: this.container.config.value,
        containerName: 'modal',
        type: 'express'
      });
  }
}

// applications/react-govuk/src/pega/containers/ActionableButton.tsx
import { PContainer } from "@labb/dx-engine";

export default function DxActionableButton(props: { container: PContainer }) {
    const { container } = props;

    function performAction() {
        container.pconnect
            .getActionsApi()
            .openLocalAction(container.config.localAction, {
                caseID: container.config.value,
                containerName: 'modal',
                type: 'express'
            });
    }

    return <div>
        <button type="button" onClick={() => performAction()}>{container.config.label}</button>
    </div>
}
