// applications/vue-reference/src/app/container-mapping/CaseSummary.vue
<script setup lang="ts">
import { PContainer } from '@labb/dx-engine';
import { DxContainer } from '@labb/vue-adapter';

defineProps<{
    container: PContainer;
}>();

</script>

<template>
    <DxContainer v-for="child in container.children"
        :key="child.id" :container="child" />
</template>

// applications/react-govuk/src/pega/containers/CaseSummary.tsx
import { PContainer } from "@labb/dx-engine";
import { GeneratePContainer } from "@labb/react-adapter";

export default function DxCaseSummary(props: { container: PContainer }) {
    const { container } = props;
    return <details className="govuk-details">
        <summary className="govuk-details__summary">
            <span className="govuk-details__summary-text">
                Case Details
            </span>
        </summary>
        <div className="govuk-details__text">
            <dl className="govuk-summary-list">
                {container.children.map(child => <GeneratePContainer key={child.id} container={child} />)}
            </dl>
        </div>
    </details>

}
