// applications/angular-rabo/src/pega/container-mapping/Default.component.ts
import { Component } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';
import { PContainer } from '@labb/dx-engine';

@Component({
  selector: 'dx-default-container',
  template: `
    <ng-template
      *ngIf="container.view"
      dxContainer
      [container]="container.view"
    ></ng-template>
    <ng-container *ngFor="let child of container.children; trackBy: trackByFn">
      <ng-template dxContainer [container]="child"></ng-template>
    </ng-container>
  `,
})
export class DefaultComponent extends PContainerComponent {
  public trackByFn(index: number, item: PContainer): string {
    return item.componentName + '_' + item.id;
  }
}

// applications/react-govuk/src/pega/containers/Default.tsx
import { PContainer } from '@labb/dx-engine';
import { GeneratePContainer } from '@labb/react-adapter';

export default function Default(props: { container: PContainer }) {
  return <>
    {props.container.view && (
      <GeneratePContainer container={props.container.view} />
    )}
    {props.container.children.map((child, index) => (
      <GeneratePContainer key={child.id + index} container={child} />
    ))}
  </>
}
