// applications/vue-hca/src/app/container-mapping/FlowContainer.vue
<script setup lang="ts">
import { ActionButton, Assignment } from '@labb/constellation-core-types';
import { FlowContainer } from '@labb/dx-engine';
import { DxContainer } from '@labb/vue-adapter';
import { ref } from 'vue';

const props = defineProps<{
  container: FlowContainer;
}>();
const todoAssignments = ref();

function click(button: ActionButton) {
  const promise = props.container.buttonClick(button);
  promise.catch((err) => handleActionError(err));
}
function handleActionError(e: Error) {
  console.error(e);
  errorMessage.value = e.message || 'Error';
}

function openAssignment(assignment: Assignment) {
  props.container.openAssignment(assignment);
}

function updateAssignments(): void {
  todoAssignments.value = props.container.getTodoAssignments();
}

updateAssignments();
props.container.updates.subscribe(() => {
  updateAssignments();
});

const errorMessage = ref<string | null>(null);
</script>

<template>
  <div>
    <template v-if="!container.hasAssignment()">
      <div v-for="assignment in todoAssignments" v-bind:key="assignment.ID">
        <div>{{ assignment.processName }} > {{ assignment.name }}</div>
        <div>Assigned to {{ assignment.assigneeInfo?.name }}</div>
        <button type="button" @click="openAssignment(assignment)">Go</button>
      </div>
      <div v-if="todoAssignments.length === 0">
        <h2 class="hca-text--headline hca-margin-bottom-15 text-center">
          Your request has been received!
        </h2>
        <p class="text-center">We will contact you as soon as possible.</p>
      </div>
    </template>
    <template v-if="container.hasAssignment()">
      <h2 class="hca-text--headline hca-margin-bottom-15">
        {{ container.getActiveViewLabel() || container.getAssignmentName() }}
      </h2>

        <DxContainer
          v-for="child in container.children"
          :key="child.id"
          :container="child"
        />

      <template v-if="container.actionButtons">
        <button
          class="hca-button hca-button--secondary hca-button--raised"
          v-for="button in container.actionButtons.secondary"
          :key="button.jsAction"
          @click="click(button)"
        >
          {{ button.name }}
        </button>
        <button
          class="hca-button hca-button--primary hca-button--raised pull-right"
          v-for="button in container.actionButtons.main"
          :key="button.jsAction"
          @click="click(button)"
        >
          {{ button.name }}
        </button>
      </template>
    </template>
  </div>
</template>

// applications/react-nhs/src/pega/containers/FlowContainer.tsx
import { Assignment } from '@labb/constellation-core-types';
import { FlowContainer } from '@labb/dx-engine';
import { GeneratePContainer } from '@labb/react-adapter';
import { useEffect, useState } from 'react';

export default function DxFlowContainer(props: { container: FlowContainer }) {
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [todoAssignments, setTodoAssignments] = useState<Assignment[]>([]);

  useEffect(() => {
    updateAssignments();
    props.container.updates.subscribe(() => {
      updateAssignments();
    });
  }, []);

  function openAssignment(assignment: Assignment) {
    props.container.openAssignment(assignment);
  }

  function updateAssignments(): void {
    setTodoAssignments(props.container.getTodoAssignments());
  }

  function handleActionError(e: Error) {
    console.error(e);
    setErrorMessage(e.message || 'Error');
  }

  return <>
    {props.container.config.caseMessages?.map(message => <div className="govuk-body" key={message}>{message}</div>)}
    {!props.container.hasAssignment() && <>
      {todoAssignments.map(assignment =>
        <div key={assignment.ID}>
          <div>{assignment.processName} {'>'} {assignment.name}</div>
          <div>Assigned to {assignment.assigneeInfo?.name}</div>
          <button type="button" onClick={() => openAssignment(assignment)}>Go</button>
        </div>
      )}
      {todoAssignments.length === 0 && <p>Thank you for your request. We will contact you as soon as possible.</p>}
    </>}
    {props.container.hasAssignment() && <div>
      <h1 className="nhsuk-heading-l">
        {props.container.getActiveViewLabel() ||
          props.container.getAssignmentName()}
      </h1>
      {props.container.children.map((child) => (
        <GeneratePContainer key={child.id} container={child} />
      ))}
      {props.container.actionButtons && (
        <div className="nhsuk-button-group">
          {props.container.actionButtons.secondary.map((button, idx) => (
            <button className={
              "nhsuk-button nhsuk-button--secondary"
              + " margin-right"
            }
              data-module="nhsuk-button"
              data-prevent-double-click="true"
              key={`secondary_${idx}`}
              onClick={(e) => {
                setErrorMessage(null);
                props.container.buttonClick(button).catch(handleActionError)
              }}
            >
              {button.name}
            </button>
          ))}
          {props.container.actionButtons.main.map((button, idx) => (
            <button className="nhsuk-button"
              data-module="nhsuk-button"
              data-prevent-double-click="true"
              key={`main_${idx}`}
              onClick={(e) => {
                setErrorMessage(null);
                props.container.buttonClick(button).catch(handleActionError)
              }}
            >
              {button.name}
            </button>
          ))}
        </div>
      )}
      {errorMessage && <div className="nhsuk-warning-text">
        <span className="nhsuk-warning-text__icon" aria-hidden="true">!</span>
        <strong className="nhsuk-warning-text__text">
          <span className="nhsuk-warning-text__assistive">Warning</span>
          Please correct the fields in the form above.
        </strong>
      </div>}
    </div>
    }</>
}
