// applications/angular-carbon/src/pega/controls/ButtonGroup.component.ts
import { Component, OnInit } from "@angular/core";
import { PContainerComponent } from "@labb/angular-adapter";
import { ListItem } from 'carbon-components-angular';

@Component({
    selector: 'dx-button-group',
    template: `
    <ibm-label
			[disabled]="container.config.readOnly"
			[helperText]="container.config.helperText"
			[invalid]="!!container.config.validatemessage"
			[invalidText]="container.config.validatemessage">
			{{container.config.label}}
        <div>
            <button *ngFor="let item of container.config.datasource"
                (click)="selected(item)"
                [ngClass]="{'bx--btn': true, 'bx--btn--field': true, 'bx--btn--secondary': item.key === container.config.value}">
                {{item.value}}
            </button>
        </div>
    </ibm-label>`,
    styles: [
        `.bx--btn {
            border-width: 1px;
            border-style: solid;
            border-color: transparent;
            margin-right: 5px;
            margin-top: 5px;
        }`
    ]
})
export class ButtonGroupComponent extends PContainerComponent implements OnInit {
    public items: ListItem[] = [];

    public ngOnInit(): void {
        this.items = this.container.config.datasource.map((item: { key: string, value: string }) => ({
            content: item.value,
            selected: item.key === this.container.config.value
        }));
    }

    public selected(item: ListItem | ListItem[]): void {
        this.container.updateFieldValue((item as any).key);
        this.container.triggerFieldChange((item as any).key);
    }
}

// applications/react-carbon/src/pega/controls/ButtonGroup.tsx
import { PContainer } from '@labb/dx-engine';

import {
  FormLabel
} from '@carbon/react';

interface DataItem {
  key: string;
  value: string;
}

interface ButtonGroupConfig {
  label: string;
  datasource: DataItem[];
  value: string;
  visibility: boolean;
}

export default function DxButtonGroup(props: { container: PContainer<ButtonGroupConfig> }): JSX.Element {
  const { label, value, datasource } = props.container.config;

  function selected(item: DataItem): void {
    props.container.updateFieldValue(item.key);
    props.container.triggerFieldChange(item.key);
  }

  return (
    <FormLabel>
      {label}
      <div className='btn-group'>
        {datasource.map(item => (
          <button
            key={item.key}
            onClick={() => selected(item)}
            className={`cds--btn cds--btn--field ${item.key === value ? 'cds--btn--secondary' : ''}`}>
            {item.value}
          </button>
        ))}
      </div>
    </FormLabel>
  );
}
