// applications/react-chase/src/pega/containers/CaseSummary.tsx
import { PContainer } from "@labb/dx-engine";
import { GeneratePContainer } from "@labb/react-adapter";
import { useState } from "react";

export default function DxCaseSummary(props: { container: PContainer }) {
    const [showSummary, setShowSummary] = useState(false);
    const { container } = props;
    return <>
        <button role="button" onClick={() => setShowSummary(!showSummary)}>
            <h3>
                <span>Show Case Details</span>
            </h3>
        </button >
        {showSummary &&
            <div role="region">
                {container.children.map(child => <GeneratePContainer key={child.id} container={child} />)}
            </div>
        }
    </>
}

// applications/vue-reference/src/app/container-mapping/CaseSummary.vue
<script setup lang="ts">
import { PContainer } from '@labb/dx-engine';
import { DxContainer } from '@labb/vue-adapter';

defineProps<{
    container: PContainer;
}>();

</script>

<template>
    <DxContainer v-for="child in container.children"
        :key="child.id" :container="child" />
</template>
