// applications/react-labb-bank/src/pega/containers/DefaultForm.tsx
import { PContainer } from '@labb/dx-engine';
import { GeneratePContainer } from '@labb/react-adapter';

export default function DefaultForm(props: { container: PContainer }) {
  const { container } = props;

  const nChildren = props.container.children[0].children.length;

  return <div style={{
    display: 'grid',
    gridTemplateColumns: `repeat(${nChildren > 1 ? container.config.NumCols ?? '1' : '1'}, minmax(0px, 1fr))`,
    gap: 'calc(0.5rem) calc(1rem)'
  }}>
    {props.container.children.map((child) => <GeneratePContainer container={child} key={child.id} />)}
  </div>
}

// applications/vue-reference/src/app/container-mapping/DefaultForm.vue
<script setup lang="ts">
import { PContainer } from '@labb/dx-engine';
import { DxContainer } from '@labb/vue-adapter';

defineProps<{
    container: PContainer;
}>();

</script>

<template>
    <div style="display: grid; grid-template-columns: repeat(2, minmax(0px, 1fr)); gap: calc(0.5rem) calc(1rem);">
        <div v-for="child in container.children[0].children" 
            :key="child.id" >
            <DxContainer :container="child" />
        </div>
    </div>
</template>
