// applications/angular-reference/src/pega/containers/Dropdown.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';
import { PContainerComponent } from '@labb/angular-adapter';

@Component({
  selector: 'dx-dropdown-control',
  template: `
  <label>{{ container.config.label }}{{ container.config.required ? ' *' : '' }}
    @if(!container.config.readOnly) {
      <select
        [id]="container.id"
        [formControl]="control"
        (change)="container.updateFieldValue(getValue($event.target))"
        (blur)="container.triggerFieldChange(getValue($event.target))"
      >
        <option disabled selected value="{undefined}">
          -- select an option --
        </option>
        @for (option of container.config.datasource; track option.key) {
          <option [value]="option.key">
            {{ option.value }}
          </option>
        }
      </select>
    } @else {
      <span>{{container.config.value}}</span>
    }
    {{ container.config.helperText }}
    {{ container.config.validatemessage }}
  </label> `,
  standalone: false
})
export class DropdownComponent extends PContainerComponent implements OnInit {
  public control = new FormControl('');

  public override ngOnInit(): void {
    super.ngOnInit();
    this.control.setValue(this.container.config.value);
    this.container.updates.subscribe(() => {
      this.control.setValue(this.container.config.value);
    });
  }

  public getValue(target: EventTarget | null): string {
    return (target as HTMLInputElement).value;
  }
}

// applications/vue-reference/src/app/container-mapping/Dropdown.vue
<script setup lang="ts">
import { PContainer } from '@labb/dx-engine';

const props = defineProps<{
    container: PContainer;
}>();

function change(event: Event) {
    props.container.updateFieldValue(getValue(event.target))
}

function blur(event: Event) {
    props.container.triggerFieldChange(getValue(event.target))
}

function getValue(target: EventTarget | null): string {
    return (target as HTMLInputElement).value;
}
</script>

<template>
    <label :for="container.id">
        {{ container.config.label }}{{container.config.required ? ' *' : '' }}
    </label>
    <select 
        :id="container.id"
        :name="container.config.label"
        :disabled="container.config.readOnly"
        @change="change"
        @blur="blur">
        <option disabled selected value="{undefined}">
            -- select an option --
        </option>
        <option
            v-for="option in container.config.datasource"
            :key="option.key" :value="option.key"
            :selected="option.key === container.config.value">
            {{ option.value }}
        </option>
    </select>
    {{ container.config.helperText }}
    {{ container.config.validatemessage }}
</template>
