// applications/react-reference/src/pega/containers/Dropdown.tsx
import { PContainer } from '@labb/dx-engine';

export default function DxDropdown(props: { container: PContainer }) {
  if (props.container.config.readOnly) {
    return <><dt>{props.container.config.label}</dt><dd>{props.container.config.value ?? '--'}</dd></>;
  }
  return <label>
    {props.container.config.label}
    {props.container.config.required ? ' *' : ''}
    <select
      onChange={(e) => props.container.updateFieldValue(e.target.value)}
      onBlur={(e) => props.container.triggerFieldChange(e.target.value)}
      disabled={props.container.config.readOnly}
      value={props.container.config.value}
    >
      <option value="" disabled={props.container.config.required}>
        Select...
      </option>
      {props.container.config.datasource.map(
        (option: { key: string; value: string }) => (
          <option key={option.key} value={option.key}>
            {option.value}
          </option>
        )
      )}
    </select>
    {props.container.config.helperText}
    {props.container.config.validatemessage}
  </label>
}

// applications/vue-reference/src/app/container-mapping/Dropdown.vue
<script setup lang="ts">
import { PContainer } from '@labb/dx-engine';

const props = defineProps<{
    container: PContainer;
}>();

function change(event: Event) {
    props.container.updateFieldValue(getValue(event.target))
}

function blur(event: Event) {
    props.container.triggerFieldChange(getValue(event.target))
}

function getValue(target: EventTarget | null): string {
    return (target as HTMLInputElement).value;
}
</script>

<template>
    <label :for="container.id">
        {{ container.config.label }}{{container.config.required ? ' *' : '' }}
    </label>
    <select 
        :id="container.id"
        :name="container.config.label"
        :disabled="container.config.readOnly"
        @change="change"
        @blur="blur">
        <option disabled selected value="{undefined}">
            -- select an option --
        </option>
        <option
            v-for="option in container.config.datasource"
            :key="option.key" :value="option.key"
            :selected="option.key === container.config.value">
            {{ option.value }}
        </option>
    </select>
    {{ container.config.helperText }}
    {{ container.config.validatemessage }}
</template>
