// applications/angular-reference/src/pega/containers/RadioButtons.component.ts
import { Component, OnInit } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';

@Component({
  selector: 'dx-radio-buttons-control',
  template: `
    <fieldset>
      <legend>
        {{ container.config.label }}{{ container.config.required ? ' *' : '' }}
      </legend>
      <ng-container *ngFor="let option of container.config.datasource">
        <label>
          <input
            type="radio"
            (change)="container.updateFieldValue(getValue($event.target))"
            (blur)="container.triggerFieldChange(getValue($event.target))"
            [checked]="container.config.value === option.key"
            [name]="container.id"
            [value]="option.key"
          />{{ option.value }}
        </label>
      </ng-container>
      {{ container.config.helperText }}
      {{ container.config.validatemessage }}
    </fieldset>
  `,
})
export class RadioButtonsComponent extends PContainerComponent implements OnInit {
  public override ngOnInit(): void {
    super.ngOnInit();
    const listType = this.container.config.listType;
    const isDatapage = listType === 'datapage';
    const configProps = this.container.pconnect.getConfigProps() as any;
    const datasource = this.container.config.datasource;
    const listSource = isDatapage ? configProps.listOutput : datasource;
    // console.log('ngOnInit', this.container.id);
    // console.log('listSource', listSource);

    // const stateProps = this.container.pconnect.getStateProps();
    // if (stateProps.value) {
    //   console.log(stateProps.value, JSON.stringify(this.container.pconnect.getFieldMetadata(stateProps.value), null, 2));
    // } else {
    //   console.log('No value');
    // }
  }

  public getValue(target: EventTarget | null): string {
    return (target as HTMLInputElement).value;
  }
}

// applications/vue-reference/src/app/container-mapping/RadioButtons.vue
<script setup lang="ts">
import { PContainer } from '@labb/dx-engine';

defineProps<{
    container: PContainer;
}>();

function getValue(target: EventTarget | null): string {
    return (target as HTMLInputElement).value;
}
</script>

<template>
    <fieldset>
        <legend>
            {{ container.config.label }}{{
                container.config.required ? ' *' : '' }}
        </legend>
        <template
            v-for="option in container.config.datasource"
            :key="option.key">
            <input type="radio"
            @change="container.updateFieldValue(getValue($event.target))"
            @blur="container.triggerFieldChange(getValue($event.target))"
            :id="container.id"
            :checked="container.config.value === option.key"
            :name="container.config.label"
            :value="option.value" />
            <label :for="container.id">{{ option.value }}</label>
            <br/>
        </template>
        {{ container.config.helperText }}
        {{ container.config.validatemessages }}
    </fieldset>
</template>
