// src/pega/containers/Region.jsx
import { GeneratePContainer } from "@labb/react-adapter";
import { Typography } from "@material-tailwind/react";

export default function DxRegion(props) {
    const { label } = props.container.config;
    return <>
        {label && <Typography variant="h6" color="blue-gray" className="mt-6">
            {label}
        </Typography>}
        {props.container.children.map((child, index) => (
            <GeneratePContainer key={child.id + index} container={child} />
        ))}
    </>
}

// applications/vue-reference/src/app/container-mapping/Region.vue
<script setup lang="ts">
import { PContainer } from '@labb/dx-engine';
import { DxContainer } from '@labb/vue-adapter';

defineProps<{
    container: PContainer;
}>();

</script>

<template>
    <p v-if="container.config.label && container.config.showLabel">{{container.config.label}}</p>
    <DxContainer v-for="child in container.children"
        :key="child.id" :container="child" />
</template>
