// applications/react-labb-bank/src/pega/containers/Region.tsx
import { PContainer } from '@labb/dx-engine';
import { GeneratePContainer } from '@labb/react-adapter';

export default function Region(props: { container: PContainer }) {
  return <>
    {props.container.children.map(child => (
      <GeneratePContainer key={child.id} container={child} />
    ))}
  </>
}

// applications/vue-reference/src/app/container-mapping/Region.vue
<script setup lang="ts">
import { PContainer } from '@labb/dx-engine';
import { DxContainer } from '@labb/vue-adapter';

defineProps<{
    container: PContainer;
}>();

</script>

<template>
    <p v-if="container.config.label && container.config.showLabel">{{container.config.label}}</p>
    <DxContainer v-for="child in container.children"
        :key="child.id" :container="child" />
</template>
