// applications/angular-rabobank/src/pega/containers/CaseSummary.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';
import { BootstrapService } from '@labb/dx-engine';

@Component({
  selector: 'dx-case-summary',
  template: `
    <a (click)="backToWorklist()" style="display: block">< Back to worklist</a>
    <a role="button" (click)="showSummary = !showSummary">
        {{showSummary ? 'Hide' : 'Show'}} Case Details
    </a>
    @if (showSummary) {
      <div role="region">
        <div>
          @for (child of container.children; track child.id) {
            <ng-container dxContainer [container]="child"/>
          }
        </div>
      </div>
    }
  `,
  encapsulation: ViewEncapsulation.None,
  standalone: false
})
export class CaseSummaryComponent extends PContainerComponent {
  showSummary = false;

  public async backToWorklist() {
    await BootstrapService.openPage('pyWorklist', 'Data-Portal', 'app');
  }
}

// applications/react-chase/src/pega/containers/CaseSummary.tsx
import { PContainer } from "@labb/dx-engine";
import { GeneratePContainer } from "@labb/react-adapter";
import { useState } from "react";

export default function DxCaseSummary(props: { container: PContainer }) {
    const [showSummary, setShowSummary] = useState(false);
    const { container } = props;
    return <>
        <button role="button" onClick={() => setShowSummary(!showSummary)}>
            <h3>
                <span>Show Case Details</span>
            </h3>
        </button >
        {showSummary &&
            <div role="region">
                {container.children.map(child => <GeneratePContainer key={child.id} container={child} />)}
            </div>
        }
    </>
}
