// applications/vue-reference/src/app/container-mapping/DefaultForm.vue
<script setup lang="ts">
import { PContainer } from '@labb/dx-engine';
import { DxContainer } from '@labb/vue-adapter';

defineProps<{
    container: PContainer;
}>();

</script>

<template>
    <div style="display: grid; grid-template-columns: repeat(2, minmax(0px, 1fr)); gap: calc(0.5rem) calc(1rem);">
        <div v-for="child in container.children[0].children" 
            :key="child.id" >
            <DxContainer :container="child" />
        </div>
    </div>
</template>

// applications/react-chase/src/pega/containers/DefaultForm.tsx
import { PContainer } from '@labb/dx-engine';
import { GeneratePContainer } from '@labb/react-adapter';

export default function DefaultForm(props: { container: PContainer }) {
  return <>
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0px, 1fr))', gap: 'calc(0.5rem) calc(1rem)' }}>
      {props.container.children.map((child, index) => (
        <div key={child.id + index}>
          <GeneratePContainer container={child} />
        </div>
      ))}
    </div>
  </>
}
