// applications/vue-hca/src/app/container-mapping/DefaultForm.vue
<script setup lang="ts">
import { PContainer } from '@labb/dx-engine';
import { DxContainer } from '@labb/vue-adapter';

defineProps<{
    container: PContainer;
}>();

</script>

<template>
    <div v-for="child in container.children[0].children" 
        :key="child.id" >
        <DxContainer :container="child" />
    </div>
</template>

// applications/react-chase/src/pega/containers/DefaultForm.tsx
import { PContainer } from '@labb/dx-engine';
import { GeneratePContainer } from '@labb/react-adapter';

export default function DefaultForm(props: { container: PContainer }) {
  return <>
    {props.container.children.map((child, index) => (
      <div key={child.id + index}>
        <GeneratePContainer container={child} />
      </div>
    ))}
  </>
}
