// applications/vue-hca/src/app/container-mapping/ModalViewContainer.vue
<script setup lang="ts">
import { ActionButton } from '@labb/constellation-core-types';
import { ModalViewContainer } from '@labb/dx-engine';
import { DxContainer } from '@labb/vue-adapter';
import { onMounted, ref, useTemplateRef } from 'vue';

const {container} = defineProps<{
    container: ModalViewContainer;
}>();
const dialogRef = useTemplateRef('dialog');
const loading = ref(false);
const errorMessage = ref<string | null>(null);

onMounted(() => {
    container.updates.subscribe(() => {
      const dialog = dialogRef.value!;
      if (container.hasContainerItems()) {
        if (!dialog.open) {
          dialog.showModal();
        }
      } else {
        if (dialog.open) {
          dialog.close();
        }
      }
    });
})

async function buttonClick(button: ActionButton): Promise<void> {
    try {
        errorMessage.value = null;
        loading.value = true;
        await container.buttonClick(button);
    } catch (e) {
        const error = e as { message: string; type: string };
        errorMessage.value = error?.message || error?.type || 'Error';
    }
    loading.value = false;
}
</script>

<template>
    <dialog ref="dialog">
      <h3>{{container.heading}}</h3>
        <DxContainer v-if="container.children.length > 0" v-for="child in container.children" :key="child.id" :container="child" />
        <button
            v-for="button of container.actionButtons.secondary"
            :key="button.actionID"
            :disabled="loading"
            @click="buttonClick(button)">
            {{ button.name }}
        </button>
        <button
            v-for="button of container.actionButtons.main"
            :key="button.actionID"
            :disabled="loading"
            @click="buttonClick(button)">
            {{ button.name }}
        </button>
    </dialog>
</template>

// applications/angular-carbon/src/pega/containers/ModalViewContainer.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';
import { ActionButton } from '@labb/constellation-core-types';
import { ModalViewContainer } from '@labb/dx-engine';

@Component({
  selector: 'dx-modal-view-container',
  template: `
    <dialog #dialog>
      <h3>{{container.heading}}</h3>
      @if (container.children.length > 0) {
        <ng-template
          dxContainer
          [container]="container.children[0]"
        ></ng-template>
      }
      @for (button of container.actionButtons.secondary; track button.actionID) {
        <button
          [disabled]="loading"
          (click)="buttonClick(button)">
          {{ button.name }}
        </button>
      }
      @for (button of container.actionButtons.main; track button.actionID) { 
        <button
          [disabled]="loading"
          (click)="buttonClick(button)">
          {{ button.name }}
        </button>
      }
    </dialog>
  `,
  standalone: false
})
export class ModalViewContainerComponent extends PContainerComponent<ModalViewContainer> implements OnInit {
  @ViewChild('dialog') public dialog!: ElementRef;
  public loading = false;
  public errorMessage?: string;

  public override ngOnInit(): void {
    super.ngOnInit();
    this.container.updates.subscribe(() => {
      if (this.container.hasContainerItems()) {
        if (!this.dialog.nativeElement.open) {
          this.dialog.nativeElement.showModal();
        }
      } else {
        if (this.dialog.nativeElement.open) {
          this.dialog.nativeElement.close();
        }
      }
    })
  }

  public async buttonClick(button: ActionButton): Promise<void> {
    try {
      delete this.errorMessage;
      this.loading = true;
      await this.container.buttonClick(button);
    } catch (e) {
      const error = e as { message: string; type: string };
      this.errorMessage = error?.message || error?.type || 'Error';
    }
    this.loading = false;
  }
}
