// applications/react-carbon/src/pega/containers/View.tsx
import { View } from "@labb/dx-engine";
import { GeneratePContainer } from "@labb/react-adapter";

export default function DxView(props: { container: View }) {
    const { container } = props;

    return <div className={`${container.pconnect.getComponentName().startsWith('Group') ? 'group' : ''} ${container.config.readOnly ? 'readOnly' : ''}`}>
        {container.config.httpMessages?.map((message: any) =>
            <div key={message.message}>
                {message.type}: {message.message}
            </div>
        )}
        {container.config.showHeading && <h2>{container.config.heading}</h2>}
        {container.config.showLabel && <p>{container.config.label}</p>}
        {(container.config.instructions && container.config.instructions !== 'none') && <p dangerouslySetInnerHTML={{ __html: container.config.instructions }}></p>}
        <div className="body">
            {props.container.children.map((child) => (
                <GeneratePContainer key={child.id} container={child} />
            ))}
        </div>
    </div>
}

// applications/angular-carbon/src/pega/containers/View.component.ts
import { Component } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';
import { View } from '@labb/dx-engine';

@Component({
  selector: 'dx-view-container',
  template: `
    <div [ngClass]="{group: container.pconnect.getComponentName().startsWith('Group'), readOnly: container.config.readOnly}">
      @for (message of container.config.httpMessages; track message.message) {
        <div>
          {{message.type}}: {{message.message}}
        </div>
      }
      @if (container.config.showHeading) { <h2>{{container.config.heading}}</h2> }
      @if (container.config.showLabel) { <span>{{container.config.label}}</span> }
      @if (container.config.instructions && container.config.instructions !== 'none') { <div [innerHtml]="container.config.instructions"></div> }
      <div class="body">
        @for (child of container.children; track child.id) {
            <ng-container dxContainer [container]="child"/>
        }
      </div>
    </div>
  `,
  standalone: false
})
export class ViewComponent extends PContainerComponent<View> {
}
