// applications/react-labb-bank/src/pega/containers/ActionableButton.tsx
import { PContainer } from "@labb/dx-engine";
import { Button } from "antd";

export default function DxActionableButton(props: { container: PContainer }) {
    const { container } = props;

    function performAction() {
        container.pconnect
            .getActionsApi()
            .openLocalAction(container.config.localAction, {
                caseID: container.config.value,
                containerName: 'modal',
                type: 'express'
            });
    }

    return <div>
        <Button onClick={() => performAction()}>{container.config.label}</Button>
    </div>
}

// applications/vue-hca/src/app/container-mapping/ActionableButton.vue
<script setup lang="ts">
import { PContainer } from '@labb/dx-engine';

const {container} = defineProps<{
    container: PContainer;
}>();
function performAction() {
    container.pconnect
        .getActionsApi()
        .openLocalAction(container.config.localAction, {
            caseID: container.config.value,
            containerName: 'modal',
            type: 'express'
        });
}
</script>

<template>
    <button type="button" @click="performAction()">{{container.config.label}}</button>
</template>
