// applications/react-reference/src/pega/containers/Checkbox.tsx
import { CheckboxProps } from '@labb/constellation-core-types';
import { PContainer } from '@labb/dx-engine';

export default function Checkbox(props: {
  container: PContainer<CheckboxProps>;
}): JSX.Element {
  function getValue(target: EventTarget & HTMLInputElement): boolean {
    return target.checked;
  }

  if (props.container.config.readOnly) {
    return <><dt>{props.container.config.caption}</dt><dd>{props.container.config.value ? props.container.config.trueLabel : props.container.config.falseLabel}</dd></>;
  }

  return <>
    <label>
      <span>
        <input
          type="checkbox"
          checked={props.container.config.value ?? false}
          onChange={(e) => {
            props.container.updateFieldValue(getValue(e.target));
            props.container.triggerFieldChange(getValue(e.target));
          }}
        />
        {props.container.config.caption}
        {props.container.config.required ? ' *' : ''}
      </span>
      {props.container.config.helperText && <span data-tooltip={props.container.config.helperText}>(?)</span>}
    </label>
    {props.container.config.validatemessage && <em>{props.container.config.validatemessage}</em>}
  </>;
}

// applications/vue-hca/src/app/container-mapping/Checkbox.vue
<script setup lang="ts">
import { PContainer } from '@labb/dx-engine';

const props = defineProps<{
    container: PContainer;
}>();

function getValue(
    target: EventTarget | null
): number | Date | boolean | string | null {
    const t: HTMLInputElement = target as HTMLInputElement;
    return t.checked;
}

function change(event: Event) {
    props.container.updateFieldValue(getValue(event.target))
}

function blur(event: Event) {
    props.container.triggerFieldChange(getValue(event.target))
}
</script>

<template>
    <div>
        <label :for="container.id">
            <input type="checkbox"
                :id="container.id"
                :name="container.config.label" 
                :checked="container.config.value"
                :disabled="container.config.readOnly"
                @change="change"
                @blur="blur" />
                {{ props.container.config.caption }}
                {{ container.config.required ? ' *' : '' }}
                <span v-if="container.config.helperText"
                    :data-tooltip="container.config.helperText">?</span>
        </label>
        {{ container.config.helperText }}
        {{ container.config.validatemessage }}
    </div>
</template>
