// applications/react-carbon/src/pega/containers/DefaultForm.tsx
import { PContainer } from '@labb/dx-engine';
import { GeneratePContainer } from '@labb/react-adapter';

export default function DxDefaultForm(props: { container: PContainer }) {
  if (props.container.children.length === 0) {
    return null;
  }
  return <div style={{ paddingTop: '15px' }}>
    {props.container.config.label && props.container.config.showLabel ? <h2>{props.container.config.label}</h2> : null}
    {props.container.config.instructions && props.container.config.instructions !== 'none' ? <div dangerouslySetInnerHTML={{ __html: props.container.config.instructions }}></div> : null}
    {props.container.children.map((child, index) => (
      <GeneratePContainer key={child.id + index} container={child} />
    ))}
  </div>
}

// applications/vue-hca/src/app/container-mapping/DefaultForm.vue
<script setup lang="ts">
import { PContainer } from '@labb/dx-engine';
import { DxContainer } from '@labb/vue-adapter';

defineProps<{
    container: PContainer;
}>();

</script>

<template>
    <div v-for="child in container.children[0].children" 
        :key="child.id" >
        <DxContainer :container="child" />
    </div>
</template>
