// applications/angular-reference/src/pega/containers/ListView.component.ts
import { Component, OnInit } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';
import { ListView } from '@labb/dx-engine';

@Component({
  selector: 'dx-list-view-container',
  template: `
    <table>
      @if(container.label) {
        <caption>{{container.label}}</caption>
      }
      <thead>
        <tr>
          @if(container.singleSelectionMode || container.multiSelectionMode) {
            <th>Select</th>
          }
          @for(col of container.fields; track col.config.name) {
            <th>{{col.config.name}}</th>
          }
        </tr>
      </thead>
      <tbody>
        @for(row of container.updatedRefList; track row.id) {
          <tr>
            @if(container.singleSelectionMode) {
              <td>
                <input type="radio" 
                  [name]="container.id" 
                  [value]="row[container.rowID]" 
                  [checked]="row[container.rowID] === container.config.value" 
                  (change)="selectRow(row)"/>
              </td>
            }
            @if(container.multiSelectionMode) {
              <td>
                <input type="checkbox"
                  [name]="container.id"
                  [value]="row[container.rowID]"
                  [checked]="row[container.rowID] === container.config.value"
                  (change)="selectRow(row, $event)"/>
              </td>
            }
            @for(col of container.fields; track col.config.name) {
              <td [innerHTML]="row[col.config.name] || '---'"></td>
            }
          </tr>
        }
      </tbody>
    </table>
  `,
  standalone: false
})
export class ListViewComponent extends PContainerComponent<ListView> implements OnInit {
  public selectRow(row: any, event?: Event) {
    this.container.selectRow(row, event && (event.target as HTMLInputElement).checked);
  }
}

// applications/vue-hca/src/app/container-mapping/ListView.vue
<script setup lang="ts">
    import { ListView } from '@labb/dx-engine';

    const props = defineProps<{
        container: ListView;
    }>();

    function  selectRow(row: any, event?: Event) {
        props.container.selectRow(row, event && (event.target as HTMLInputElement).checked);
    }
</script>

<template>
    <table>
    <caption v-if="container.label">{{container.label}}</caption>
      <thead>
        <tr>
            <th v-if="container.singleSelectionMode || container.multiSelectionMode"></th>  
            <th v-for="col in container.fields" :key="col.config.name">{{col.config.label}}</th>
        </tr>
      </thead>
      <tbody>
          <tr v-for="row in container.updatedRefList" :key="row.id">
              <td v-if="container.singleSelectionMode">
                <input type="radio" 
                  :name="container.id" 
                  :value="row[container.rowID]" 
                  :checked="row[container.rowID] === container.config.value" 
                  @change="selectRow(row)"/>
              </td>
              <td v-if="container.multiSelectionMode">
                <input type="checkbox"
                    :name="container.id"
                    :value="row[container.rowID]"
                  :checked="row[container.rowID] === container.config.value"
                  @change="selectRow(row, $event)"/>
              </td>
              <td v-for="col of container.fields" :key="col.config.name" v-html="row[col.config.name] || '---'"></td>
          </tr>
      </tbody>
    </table>
</template>
