// applications/react-reference/src/pega/containers/MaskedInput.tsx
import { PContainer } from "@labb/dx-engine";
import { ChangeEvent, useEffect, useRef } from "react";
import IMask from 'imask';

export default function DxMaskedInput(props: { container: PContainer }) {
    const input = useRef(null);
    const { container } = props;

    useEffect(() => {
        if (input.current) {
            const maskOptions = {
                mask: container.config.mask,
                definitions: {
                    // defaults are '0', 'a', '*'
                    // You can extend by adding other characters
                    A: /[A-Z]/
                }
            }
            const mask = IMask(input.current, maskOptions);
            mask.value = container.config.value;
        }
    }, [input.current])


    function getValue(event: ChangeEvent) {
        return (event.target as HTMLInputElement).value;
    }

    return <>
        {container.config.readOnly && <>
            <dt>{container.config.label}</dt>
            <dd>{container.config.value ?? '--'}</dd>
        </>}
        {!container.config.readOnly && <>
            <label htmlFor={container.id}>
                {container.config.label}{container.config.required ? ' *' : ''} ({container.config.mask})
                {container.config.helperText &&
                    <span data-tooltip={container.config.helperText}>?</span>
                }
            </label>
            <input
                ref={input}
                id={container.id}
                type="text"
                placeholder={container.config.placeholder}
                onBlur={e => {
                    container.updateFieldValue(getValue(e));
                    container.triggerFieldChange(getValue(e));
                }}
            />
        </>}
        {container.config.validatemessage && <span>{container.config.validatemessage}</span>}
    </>
}

// applications/vue-hca/src/app/container-mapping/MaskedInput.vue
<script setup lang="ts">
import { PContainer } from '@labb/dx-engine';
import { onMounted, useTemplateRef } from 'vue';
import IMask from 'imask';

const {container} = defineProps<{
    container: PContainer;
}>();
function getValue(target: EventTarget | null) {
    return (target as HTMLInputElement).value;
}
const input = useTemplateRef('masked-input');
onMounted(() => {
  const maskOptions = {
      mask: container.config.mask,
      definitions: {
        // defaults are '0', 'a', '*'
        // You can extend by adding other characters
        A: /[A-Z]/
      }
    }
    IMask(input.value!, maskOptions);
});
</script>

<template>
    <dt v-if="container.config.readOnly">{{ container.config.label }}</dt>
    <dd v-if="container.config.readOnly">{{container.config.value ?? '--'}}</dd>
    <HcaFormField
    v-if="!container.config.readOnly"
    :label="container.config.label"
    :for="container.id"
    :helperText="container.config.helperText"
    :errorMessage="container.config.validatemessage"
  >
    <input
      :id="container.id"
      :name="container.config.label"
      :value="container.config.value"
      type="text"
      autocomplete="off"
      @change="container.updateFieldValue(getValue($event.target))"
      @blur="container.triggerFieldChange(getValue($event.target))"
      class="hca-form-field__input ember-text-field ember-view"
    />
  </HcaFormField>
</template>
