// applications/react-labb-bank/src/pega/containers/ModalViewContainer.tsx
import { ActionButton } from "@labb/constellation-core-types";
import { ModalViewContainer } from "@labb/dx-engine";
import { GeneratePContainer } from "@labb/react-adapter";
import { Button, Modal } from "antd";
import { useState } from "react";

export default function DxModalViewContainer(props: { container: ModalViewContainer }) {
    const [loading, setLoading] = useState(false);
    const [open, setOpen] = useState(false);
    const [errorMessage, setErrorMessage] = useState<string | null>(null);
    const { container } = props;

    async function buttonClick(button: ActionButton): Promise<void> {
        try {
            setErrorMessage(null);
            setLoading(true);
            await container.buttonClick(button);
        } catch (e) {
            const error = e as { message: string; type: string };
            setErrorMessage(error?.message || error?.type || 'Error');
        }
        setLoading(false);
    }
    props.container.updates.subscribe(() => {
        setOpen(props.container.hasContainerItems());
    })

    return <>
        <Modal
            title={container.heading}
            open={open}
            confirmLoading={loading}
            footer={[
                ...props.container.actionButtons.secondary.map(button =>
                    <Button key={button.actionID}
                        disabled={loading}
                        onClick={() => buttonClick(button)}>
                        {button.name}
                    </Button>
                ),
                ...props.container.actionButtons.main.map(button =>
                    <Button key={button.actionID}
                        disabled={loading}
                        onClick={() => buttonClick(button)}>
                        {button.name}
                    </Button>
                )
            ]}
        >
            {props.container.children.map(child => (
                <GeneratePContainer key={child.id} container={child} />
            ))}
        </Modal>
    </>
}

// applications/vue-hca/src/app/container-mapping/ModalViewContainer.vue
<script setup lang="ts">
import { ActionButton } from '@labb/constellation-core-types';
import { ModalViewContainer } from '@labb/dx-engine';
import { DxContainer } from '@labb/vue-adapter';
import { onMounted, ref, useTemplateRef } from 'vue';

const {container} = defineProps<{
    container: ModalViewContainer;
}>();
const dialogRef = useTemplateRef('dialog');
const loading = ref(false);
const errorMessage = ref<string | null>(null);

onMounted(() => {
    container.updates.subscribe(() => {
      const dialog = dialogRef.value!;
      if (container.hasContainerItems()) {
        if (!dialog.open) {
          dialog.showModal();
        }
      } else {
        if (dialog.open) {
          dialog.close();
        }
      }
    });
})

async function buttonClick(button: ActionButton): Promise<void> {
    try {
        errorMessage.value = null;
        loading.value = true;
        await container.buttonClick(button);
    } catch (e) {
        const error = e as { message: string; type: string };
        errorMessage.value = error?.message || error?.type || 'Error';
    }
    loading.value = false;
}
</script>

<template>
    <dialog ref="dialog">
      <h3>{{container.heading}}</h3>
        <DxContainer v-if="container.children.length > 0" v-for="child in container.children" :key="child.id" :container="child" />
        <button
            v-for="button of container.actionButtons.secondary"
            :key="button.actionID"
            :disabled="loading"
            @click="buttonClick(button)">
            {{ button.name }}
        </button>
        <button
            v-for="button of container.actionButtons.main"
            :key="button.actionID"
            :disabled="loading"
            @click="buttonClick(button)">
            {{ button.name }}
        </button>
    </dialog>
</template>
