// applications/vue-reference/src/app/container-mapping/Checkbox.vue
<script setup lang="ts">
import { PContainer } from '@labb/dx-engine';

const props = defineProps<{
    container: PContainer;
}>();

function getValue(
    target: EventTarget | null
): number | Date | boolean | string | null {
    const t: HTMLInputElement = target as HTMLInputElement;
    return t.checked;
}

function change(event: Event) {
    props.container.updateFieldValue(getValue(event.target))
}

function blur(event: Event) {
    props.container.triggerFieldChange(getValue(event.target))
}
</script>

<template>
    <input type="checkbox"
        :id="container.id"
        :name="container.config.label" 
        :value="container.config.value"
        :disabled="container.config.readOnly"
        @change="change" @blur="blur" />
    <label :for="container.id">
        {{ props.container.config.caption }}
        {{ container.config.required ? ' *' : '' }}
        <span v-if="container.config.helperText"
            :data-tooltip="container.config.helperText">?</span>
    </label>
    {{ container.config.validatemessage }}
</template>

// applications/react-centraalbeheer/src/pega/containers/Checkbox.tsx
import { PContainer } from '@labb/dx-engine';

export default function Checkbox(props: {
  container: PContainer;
}): JSX.Element {
  function getValue(target: EventTarget & HTMLInputElement): boolean {
    return target.checked;
  }
  if (props.container.config.readOnly) {
    return <><dt>{props.container.config.caption}</dt><dd>{props.container.config.value ? props.container.config.trueLabel : props.container.config.falseLabel}</dd></>;
  }

  return <>
    <label>
      {props.container.config.required ? ' *' : ''}
      <input
        type="checkbox"
        onChange={(e) => {
          props.container.updateFieldValue(getValue(e.target));
          props.container.triggerFieldChange(getValue(e.target));
        }}
      />
      {props.container.config.caption}
    </label>
    {props.container.config.helperText}
    {props.container.config.validatemessage}
  </>;
}
