// applications/angular-rabobank/src/pega/containers/Checkbox.component.ts
import { Component } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';

@Component({
  selector: 'dx-checkbox',
  template: `
  @if (container.config.readOnly) {
      <dx-input-wrapper
          [label]="container.config.label" 
          [labelEnd]="container.config.helperText"
          [errorMessage]="container.config.validatemessage">
          {{container.config.value ? container.config.trueLabel : container.config.falseLabel}}
      </dx-input-wrapper>
    } @else {
      <dx-checkbox-control
        [label]="container.config.caption" 
        [labelEnd]="container.config.helperText"
        [errorMessage]="container.config.validatemessage"
        [checked]="container.config.value">
          <input
            [id]="container.id"
            type="checkbox"
            [attr.readonly]="container.config.readOnly"
            [value]="container.config.value"
            (change)="change($event.target)"
          />
      </dx-checkbox-control>
    }
   `,
  standalone: false
})
export class CheckboxComponent extends PContainerComponent {
  public change(target: EventTarget | null) {
    if (!target) return;
    const val = (target as HTMLInputElement).checked;
    this.container.updateFieldValue(val);
    this.container.triggerFieldChange(val);
  }
}

// applications/react-centraalbeheer/src/pega/containers/Checkbox.tsx
import { PContainer } from '@labb/dx-engine';

export default function Checkbox(props: {
  container: PContainer;
}): JSX.Element {
  function getValue(target: EventTarget & HTMLInputElement): boolean {
    return target.checked;
  }
  if (props.container.config.readOnly) {
    return <><dt>{props.container.config.caption}</dt><dd>{props.container.config.value ? props.container.config.trueLabel : props.container.config.falseLabel}</dd></>;
  }

  return <>
    <label>
      {props.container.config.required ? ' *' : ''}
      <input
        type="checkbox"
        onChange={(e) => {
          props.container.updateFieldValue(getValue(e.target));
          props.container.triggerFieldChange(getValue(e.target));
        }}
      />
      {props.container.config.caption}
    </label>
    {props.container.config.helperText}
    {props.container.config.validatemessage}
  </>;
}
