// applications/angular-athora/src/pega/containers/Group.component.ts
import { Component } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';
import { PContainer } from '@labb/dx-engine';

@Component({
  selector: 'dx-group-container',
  template: `
      <h1 *ngIf="container.config.heading">{{container.config.heading}}</h1>
      <div *ngIf="container.config.instructions" [innerHtml]="container.config.instructions | translate"></div>
      <form class="dip-ext-grid-form">
        <ng-container *ngFor="let child of container.children; trackBy: trackByFn">
          <ng-template dxContainer [container]="child"></ng-template>
        </ng-container>
      </form>
  `,
})
export class GroupComponent extends PContainerComponent {
  public trackByFn(index: number, item: PContainer): string {
    return item.componentName + '_' + item.id;
  }
}

// applications/react-labb-bank/src/pega/containers/Group.tsx
import { PContainer } from '@labb/dx-engine';
import { GeneratePContainer } from '@labb/react-adapter';
import { Card } from 'antd';

export default function Group(props: { container: PContainer }) {
  return <Card title={props.container.config.heading} style={{ marginBottom: '15px' }}>
    {
      props.container.config.instructions && !['none', 'casestep'].includes(props.container.config.instructions) && <div dangerouslySetInnerHTML={{ __html: props.container.config.instructions }}></div>
    }
    {props.container.children.map(child => (
      <GeneratePContainer key={child.id} container={child} />
    ))}
  </Card>
}
