// applications/angular-citibank/src/pega/containers/Dropdown.component.ts
import { Component } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';
import { PicklistProps } from '@labb/constellation-core-types';
import { PContainer } from '@labb/dx-engine';

@Component({
  selector: 'dx-dropdown-control',
  template: `
    <cds-form-field [label]="container.config.label" [errorMessage]="container.config.validatemessage">
      <cds-dropdown (selected)="update($event)">
          @for (option of container.config.datasource; track option.key) {
            <cds-option [value]="option.value"></cds-option>
          }
      </cds-dropdown>
    </cds-form-field>
  `,
})
export class DropdownComponent extends PContainerComponent<PContainer<PicklistProps>> {
  public update(value: string) {
    this.container.updateFieldValue(value);
    this.container.triggerFieldChange(value);
  }
}

// applications/react-cmcmarkets/src/pega/containers/Dropdown.tsx
import { PContainer } from '@labb/dx-engine';
import CmCDropdown from '../../cmc-design/cmc-dropdown';
import CmCFormControl from '../../cmc-design/cmc-form-control';

export default function DxDropdown(props: { container: PContainer }) {
  return <CmCFormControl
    label={props.container.config.label}
    helperText={props.container.config.helperText}>
    <CmCDropdown
      errorMessage={props.container.config.validatemessage}
      value={props.container.config.value}
      options={props.container.config.datasource}
      selected={(key: string) => {
        props.container.updateFieldValue(key);
        props.container.triggerFieldChange(key);
      }} />
  </CmCFormControl>
}
