// applications/react-carbon/src/pega/controls/AddressLookup.tsx
import {
    FormLabel,
    TextInput,
    Tile,
    Table,
    TableHead,
    TableHeader,
    TableRow,
    TableBody,
    TableCell,
} from "@carbon/react"
import { useState } from "react";

interface Address {
    OrganisationName: string;
    BuildingNumber: number;
    AddressLine: string;
    Postcode: string;
    Town: string;
    pyGUID: string;
}

export default function AddressLookup() {
    const [model, setModel] = useState<any>(null);
    const [address, setAddress] = useState<Address | null>(null);

    async function search() {
        const searchResult = (await window.PCore.getDataApiUtils().getData<Address>('D_AddressesList', {})).data.data;
        if (searchResult) {
            const data = ['OrganisationName', 'BuildingNumber', 'AddressLine', 'Postcode', 'Town'];
            setModel({
                header: data,
                data: searchResult.map(item => [
                    item.OrganisationName,
                    item.BuildingNumber,
                    item.AddressLine,
                    item.Postcode,
                    item.Town
                ]),
                addresses: searchResult
            });
        }
    }
    return <>
        {!model && !address && <TextInput id="zipcode" type="text" labelText="Zipcode" onChange={() => null} onBlur={e => e.target.value && search()} />}
        {model && !address &&
            <Table>
                <TableHead>
                    <TableRow>
                        {model.header.map((header: any) => (
                            <TableHeader key={header}>{header}</TableHeader>
                        ))}
                    </TableRow>
                </TableHead>
                <TableBody>
                    {model.data.map((row: any, idx: number) => (
                        <TableRow key={idx} onClick={() => setAddress(model.addresses[idx])}>
                            {row.map((cell: any) => (
                                <TableCell key={cell}>{cell}</TableCell>
                            ))}
                        </TableRow>
                    ))}
                </TableBody>
            </Table>
        }
        {address && <Tile>
            {address.OrganisationName} {address.BuildingNumber} {address.AddressLine} {address.Postcode} {address.Town}
        </Tile>}
    </>
}

// applications/angular-citibank/src/pega/containers/AddressLookup.component.ts
import { Component, OnInit } from "@angular/core";
import { FormControl } from "@angular/forms";
import { PContainerComponent } from "@labb/angular-adapter";
import { take } from "rxjs";

interface Address {
    OrganisationName: string;
    BuildingNumber: number;
    AddressLine: string;
    Postcode: string;
    Town: string;
    pyGUID: string;
}

@Component({
    selector: 'dx-address-lookup',
    template: `<label *ngIf="!searchResults && !address"> Zipcode
    <input type="text" [formControl]="control">
  </label>
  <table *ngIf="searchResults">
    <thead>
      <tr>
        <th *ngFor="let h of model.header">{{h}}</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let row of model.data; index as i" (click)="selectAddress(i)">
        <td *ngFor="let col of row">{{col}}</td>
      </tr>
    </tbody>
  
  <div *ngIf="address">
    {{address.OrganisationName}} {{address.BuildingNumber}} {{address.AddressLine}} {{address.Postcode}} {{address.Town}}
  </div>`
})
export class AddressLookupComponent extends PContainerComponent implements OnInit {
    public control = new FormControl('', { updateOn: 'blur' });
    public searchResults: Address[] | null = null;
    public address: Address | null = null;

    public model = {
      header : [] as string [],
      data : [] as (number | string) [][],
    };


    public override ngOnInit(): void {
      super.ngOnInit();
        this.control.valueChanges.pipe(take(1)).subscribe(async () => {
            this.searchResults = (await window.PCore.getDataApiUtils().getData<Address>('D_AddressesList', {})).data.data;
            if (this.searchResults) {
                const data = ['OrganisationName', 'BuildingNumber', 'AddressLine', 'Postcode', 'Town'];
                this.model.header = data;
                this.model.data = this.searchResults.map(item => [
                    item.OrganisationName,
                    item.BuildingNumber,
                    item.AddressLine,
                    item.Postcode,
                    item.Town
                ]);
            }
        })
    }

    public selectAddress(index: number): void {
        if (this.searchResults) {
            this.address = this.searchResults[index];
            this.searchResults = null;
            this.container.updateFieldValue(this.address.pyGUID);
        }
    }
}
