// applications/react-lvcyclery/src/pega/containers/DetailsThreeColumns.tsx
import { PContainer } from "@labb/dx-engine";
import { GeneratePContainer } from "@labb/react-adapter";

export default function DxDetailsThreeColumns(props: { container: PContainer }) {
    return <div className="three-column">
        <div>
            {props.container.children[0].children.map(child => <GeneratePContainer container={child} />)}
        </div>
        <div>
            {props.container.children[1].children.map(child => <GeneratePContainer container={child} />)}
        </div>
        <div>
            {props.container.children[1].children.map(child => <GeneratePContainer container={child} />)}
        </div>
    </div>;
}

// applications/angular-citibank/src/pega/containers/DetailsThreeColumns.ts
import { Component } from "@angular/core";
import { PContainerComponent } from "@labb/angular-adapter";

@Component({
    selector: 'dx-details-three-columns',
    template: `
        <div class="three-column">
            <div>
                <ng-template
                    *ngFor="let child of container.children[0].children"
                    dxContainer
                    [container]="child"
                ></ng-template>
            </div>
            <div>
                <ng-template
                    *ngFor="let child of container.children[1].children"
                    dxContainer
                    [container]="child"
                ></ng-template>
            </div>
            <div>
                <ng-template
                    *ngFor="let child of container.children[2].children"
                    dxContainer
                    [container]="child"
                ></ng-template>
            </div>
        </div>
    `,
    styles: [
        `
        .three-column {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: calc(1rem);
        }
        `
    ]
})
export class DetailsThreeColumnComponent extends PContainerComponent { }
