// applications/vue-hca/src/app/container-mapping/MultiSelect.vue
<script setup lang="ts">
import { Multiselect } from '@labb/dx-engine';

const {container} = defineProps<{
    container: Multiselect;
}>();
function search(event: Event) {
    const value = (event.target as HTMLInputElement).value
    container.onSearchHandler(value);
}
</script>

<template>
    <label>
        {{container.config.label}}
        <input type="text" @blur="search($event)">
    </label>
    <label v-for="item in container.itemsTree" :key="item.id">
        <input type="checkbox" :checked="item.selected" 
            @change="container.toggleItem(item.id!)">{{item.primary}}
    </label>
</template>

// applications/angular-citibank/src/pega/containers/Multiselect.component.ts
import { Component } from "@angular/core";
import { PContainerComponent } from "@labb/angular-adapter";
import { Multiselect } from "@labb/dx-engine";

@Component({
    selector: 'dx-multi-select',
    template: `
        <label>
            {{container.config.label}}
            <input type="text" (blur)="container.onSearchHandler($event)">
        </label>
        <label *ngFor="let item of container.itemsTree">
            <input type="checkbox" [checked]="item.selected" (change)="container.toggleItem(item.id!)">{{item.primary}}
        </label>
    `
})
export class MultiselectComponent extends PContainerComponent<Multiselect> {
}
