// applications/react-hsbc/src/pega/containers/RadioButtons.tsx
import { PicklistProps } from '@labb/constellation-core-types';
import { PContainer } from '@labb/dx-engine';
import HsbcFormFieldset from 'applications/react-hsbc/design-system/hsbc-form-fieldset';
import HsbcRadio from 'applications/react-hsbc/design-system/hsbc-radio';

export default function DxRadioButtons(props: { container: PContainer<PicklistProps> }) {
  return <HsbcFormFieldset label={props.container.config.label}
    id={props.container.id}
    hint={props.container.config.helperText}
    error={props.container.config.validatemessage}>
    <HsbcRadio id={props.container.id}
      options={props.container.config.datasource}
      value={props.container.config.value}
      onChange={v => {
        props.container.updateFieldValue(v)
        props.container.triggerFieldChange(v)
      }} />
  </HsbcFormFieldset>
}

// applications/angular-citibank/src/pega/containers/RadioButtons.component.ts
import { Component, OnInit } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';
import { PicklistProps } from '@labb/constellation-core-types';
import { PContainer } from '@labb/dx-engine';

@Component({
  selector: 'dx-radio-buttons-control',
  template: `
    <h5>{{container.config.label}}</h5>
    <cds-form-field [errorMessage]="container.config.validatemessage">
        <cds-radio-group [direction]="container.config.datasource.length > 2 ? 'column' : 'row'">
            @for (option of container.config.datasource; track option.key) {
              <cds-radio [label]="option.value" [for]="container.id+option.key">
                  <input cdsInput type="radio" [name]="container.id" [id]="container.id+option.key" [value]="option.key" (change)="change(option.key)">
              </cds-radio>
            }
        </cds-radio-group>
    </cds-form-field>
  `,
})
export class RadioButtonsComponent extends PContainerComponent<PContainer<PicklistProps>> {
    public change(value: string) {
      this.container.updateFieldValue(value);
      this.container.triggerFieldChange(value);
    }
}
