// applications/react-labb-bank/src/pega/containers/RadioButtons.tsx
import { PicklistProps } from '@labb/constellation-core-types';
import { PContainer } from '@labb/dx-engine';
import { Radio, Form } from 'antd';
import { RadioChangeEventTarget } from 'antd/es/radio';

export default function RadioButtons(props: {
  container: PContainer<PicklistProps>;
}): JSX.Element {
  function getValue(target: RadioChangeEventTarget): string {
    return target.value;
  }

  if (props.container.config.readOnly) {
    return (
      <Form.Item label={props.container.config.label}>
        <div>{props.container.config.value ?? '--'}</div>
      </Form.Item>
    );
  }

  return (
    <Form.Item
      label={props.container.config.label}
      required={props.container.config.required}
      help={props.container.config.helperText}
      validateStatus={props.container.config.validatemessage ? 'error' : ''}
      extra={props.container.config.validatemessage}
    >
      <Radio.Group
        style={{
          display: 'flex',
          flexDirection: 'column',
          gap: 8,
        }}
        value={props.container.config.value}
        onChange={(e) => {
          props.container.updateFieldValue(getValue(e.target));
          props.container.triggerFieldChange(getValue(e.target));
        }}
      >
        {props.container.config.datasource?.map(
          (option: { key: string; value: string }) => (
            <Radio key={option.key} value={option.key}>
              {option.value}
            </Radio>
          )
        )}
      </Radio.Group>
    </Form.Item>
  );
}

// applications/angular-citibank/src/pega/containers/RadioButtons.component.ts
import { Component, OnInit } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';
import { PicklistProps } from '@labb/constellation-core-types';
import { PContainer } from '@labb/dx-engine';

@Component({
  selector: 'dx-radio-buttons-control',
  template: `
    <h5>{{container.config.label}}</h5>
    <cds-form-field [errorMessage]="container.config.validatemessage">
        <cds-radio-group [direction]="container.config.datasource.length > 2 ? 'column' : 'row'">
            @for (option of container.config.datasource; track option.key) {
              <cds-radio [label]="option.value" [for]="container.id+option.key">
                  <input cdsInput type="radio" [name]="container.id" [id]="container.id+option.key" [value]="option.key" (change)="change(option.key)">
              </cds-radio>
            }
        </cds-radio-group>
    </cds-form-field>
  `,
})
export class RadioButtonsComponent extends PContainerComponent<PContainer<PicklistProps>> {
    public change(value: string) {
      this.container.updateFieldValue(value);
      this.container.triggerFieldChange(value);
    }
}
