// applications/vue-hca/src/app/container-mapping/Default.vue
<script setup lang="ts">
import { PContainer } from '@labb/dx-engine';
import { DxContainer } from '@labb/vue-adapter';
import { ref } from 'vue';

const {container} = defineProps<{
    container: PContainer;
}>();
const val = ref(container.children.length);

const id = setInterval(() => {
    val.value = container.children.length;
    if(val.value > 0) {
        window.clearInterval(id);
    }
},100);
</script>

<template>
    <div :data-children="val">
        <DxContainer v-for="child in container.children"
        :key="child.id" :container="child" />
    </div>
</template>

// applications/react-hsbc/src/pega/containers/Default.tsx
import { PContainer } from '@labb/dx-engine';
import { GeneratePContainer } from '@labb/react-adapter';

export default function DxDefault(props: { container: PContainer }) {
  return <>
    {props.container.children.map((child, index) => (
      <GeneratePContainer key={child.id + index} container={child} />
    ))}
  </>
}
