// applications/vue-hca/src/app/container-mapping/DxFlowContainer.vue
<script setup lang="ts">
import { ActionButton, Assignment } from '@labb/constellation-core-types';
import { FlowContainer } from '@labb/dx-engine';
import { DxContainer } from '@labb/vue-adapter';
import { ref } from 'vue';

const props = defineProps<{
  container: FlowContainer;
}>();
const todoAssignments = ref();

function click(button: ActionButton) {
  const promise = props.container.buttonClick(button);
  promise.catch((err) => handleActionError(err));
}
function handleActionError(e: Error) {
  console.error(e);
  errorMessage.value = e.message || 'Error';
}

function openAssignment(assignment: Assignment) {
  props.container.openAssignment(assignment);
}

function updateAssignments(): void {
  todoAssignments.value = props.container.getTodoAssignments();
}

updateAssignments();
props.container.updates.subscribe(() => {
  updateAssignments();
});

const errorMessage = ref<string | null>(null);
</script>

<template>
  <div>
    <template v-if="!container.hasAssignment()">
      <div v-for="assignment in todoAssignments" v-bind:key="assignment.ID">
        <div>{{ assignment.processName }} > {{ assignment.name }}</div>
        <div>Assigned to {{ assignment.assigneeInfo?.name }}</div>
        <button type="button" @click="openAssignment(assignment)">Go</button>
      </div>
      <div v-if="todoAssignments.length === 0">
        <h2 class="hca-text--headline hca-margin-bottom-15 text-center">
          Your request has been received!
        </h2>
        <p class="text-center">We will contact you as soon as possible.</p>
      </div>
    </template>
    <template v-if="container.hasAssignment()">
      <h2 class="hca-text--headline hca-margin-bottom-15">
        {{ container.getActiveViewLabel() || container.getAssignmentName() }}
      </h2>

      <div class="flex">
        <DxContainer
          v-for="child in container.children"
          :key="child.id"
          :container="child"
        />
      </div>

      <template v-if="container.actionButtons">
        <button
          class="hca-button hca-button--secondary hca-button--raised"
          v-for="button in container.actionButtons.secondary"
          :key="button.jsAction"
          @click="click(button)"
        >
          {{ button.name }}
        </button>
        <button
          class="hca-button hca-button--primary hca-button--raised pull-right"
          v-for="button in container.actionButtons.main"
          :key="button.jsAction"
          @click="click(button)"
        >
          {{ button.name }}
        </button>
      </template>
    </template>
  </div>
</template>

// applications/react-hsbc/src/pega/containers/DxFlowContainer.tsx
import { FlowContainer } from '@labb/dx-engine';
import { GeneratePContainer } from '@labb/react-adapter';
import HsbcButton from 'applications/react-hsbc/design-system/hsbc-button';
import HsbcButtonGroup from 'applications/react-hsbc/design-system/hsbc-button-group';
import HsbcContainer from 'applications/react-hsbc/design-system/hsbc-container';
import HsbcProgressBar from 'applications/react-hsbc/design-system/hsbc-progress-bar';
import { useState } from 'react';

export default function DxFlowContainer(props: { container: FlowContainer }) {
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  function handleActionError(e: Error) {
    console.error(e);
    setErrorMessage(e?.message || 'Error');
  }

  if (!props.container.hasAssignment()) {
    return <div>No active assignment</div>;
  }

  return <>
    <HsbcContainer>
      <HsbcProgressBar
        name={
          window.PCore.getStore().getState().data[props.container.pconnect.getContextName()].caseInfo.stageLabel
        }
        currentStep={props.container.navigation?.steps.findIndex(step => step.visited_status === 'current')}
        totalSteps={props.container.navigation?.steps.length} />
    </HsbcContainer>
    <HsbcContainer title={props.container.getActiveViewLabel() ||
      props.container.getAssignmentName()}>
      {props.container.children.map((child) => (
        <GeneratePContainer key={child.id} container={child} />
      ))}
    </HsbcContainer>
    {
      props.container.actionButtons && (
        <HsbcContainer>
          <HsbcButtonGroup>
            <>
              {props.container.actionButtons.main.map((button) => (
                <HsbcButton type="primary"
                  key={button.actionID}
                  label={button.name}
                  onClick={() =>
                    props.container.buttonClick(button).catch(handleActionError)
                  } />
              ))}
              {props.container.actionButtons.secondary
                .filter(button => button.actionID === 'back')
                .map((button) => (
                  <HsbcButton type="secondary"
                    key={button.actionID}
                    label={button.name}
                    onClick={() =>
                      props.container.buttonClick(button).catch(handleActionError)
                    } />
                ))}
            </>
          </HsbcButtonGroup>
        </HsbcContainer>
      )
    }
    {errorMessage && <div>{errorMessage}</div>}
  </>
}
