// applications/angular-citibank/src/pega/containers/Location.component.ts
import { AfterViewInit, Component, ElementRef, ViewChild } from "@angular/core";
import { FormControl } from "@angular/forms";
import { PContainerComponent } from "@labb/angular-adapter";
import { Location } from "@labb/dx-engine";
import { CdsDropdownService } from "../../design-system/cds-dropdown/cds-dropdown.service";

@Component({
    selector: 'dx-location',
    template: `
        <cds-form-field [label]="container.config.label" [for]="container.id">
            @if(this.container.config.readOnly) {
                {{container.config.value}}
            } @else {
            <input cdsInput
                #input
                type="text"
                [formControl]="searchControl"
                [name]="container.id"
                (blur)="updateSearch()">
            }
        </cds-form-field>
        @if(suggestions.length > 0) {
            <cds-form-field [label]="container.config.label" [errorMessage]="container.config.validatemessage">
                <cds-dropdown (selected)="select($event)" [value]="container.config.value" [disabled]="container.config.readOnly">
                    @for(suggestion of suggestions; track suggestion) {
                        <cds-option (click)="submit(suggestion)" [value]="suggestion"></cds-option>
                    }
                </cds-dropdown>
            </cds-form-field>
        }
        <div #map style="height: 25rem"></div>
    `,
    providers: [CdsDropdownService],
    standalone: false
})
export class LocationComponent extends PContainerComponent<Location> implements AfterViewInit {
    @ViewChild('map') map!: ElementRef;
    public searchControl = new FormControl();
    public selectControl = new FormControl('');
    public suggestions: string[] = [];

    public constructor(private dropdownService: CdsDropdownService) {
        super();
    }

    public async ngAfterViewInit(): Promise<void> {
        await this.container.loadMap(this.map.nativeElement);
        this.searchControl.setValue(this.container.config.value);
    }

    public async updateSearch() {
        this.suggestions = await this.container.getPlacePredictions(this.searchControl.value);
    }

    public submit(value: string) {
        this.dropdownService.submit(value);
    }

    public async select(value: string) {
        this.container.updateFieldValue(value);
        this.container.triggerFieldChange(value);
    }
}

// applications/react-hsbc/src/pega/containers/Location.tsx
import { Location } from "@labb/dx-engine";
import HsbcFormElement from "applications/react-hsbc/design-system/hsbc-form-element";
import HsbcInput from "applications/react-hsbc/design-system/hsbc-input";
import HsbcSelect from "applications/react-hsbc/design-system/hsbc-select";
import { ChangeEvent, useEffect, useRef, useState } from "react";

export default function DxLocation(props: { container: Location }) {
    const map = useRef(null);
    const [suggestions, setSuggestions] = useState<string[]>([]);
    const [searchValue, setSearchValue] = useState<string>('');
    const { container } = props;

    useEffect(() => {
        (async () => {
            if (map.current) {
                await container.loadMap(map.current);
            }
        })();
    }, [map.current]);

    async function updateSearch(value: string) {
        setSearchValue(value)
        setSuggestions(await container.getPlacePredictions(value));
    }

    async function select(value: string) {
        container.updateFieldValue(value);
        container.triggerFieldChange(value);
    }

    return <>
        {container.config.readOnly && <>
            <dt>{props.container.config.label}</dt><dd>{props.container.config.value ?? '--'}</dd>
        </>}
        {!container.config.readOnly && <>
            <HsbcFormElement
                label={props.container.config.label}
                id={props.container.id}
                hint={props.container.config.helperText}
                error={props.container.config.validatemessage}>
                <>
                    <HsbcInput id={props.container.id}
                        type="text"
                        invalid={props.container.config.validatemessage}
                        value={searchValue}
                        onChange={(event) => updateSearch(event)}
                    />
                    {suggestions.length > 0 &&
                        <HsbcSelect id={props.container.id}
                            options={suggestions.map(suggestion => ({ key: suggestion, value: suggestion }))}
                            value={props.container.config.value}
                            onChange={v => select(v)} />
                    }
                </>
            </HsbcFormElement>
            {container.config.value && <div ref={map} style={{ height: '25rem' }}></div>}
        </>
        }
    </>
}
