// applications/react-govuk/src/pega/controls/Attachment.tsx
import { Attachment as PAttachment } from '@labb/dx-engine';

export default function Attachment(props: {
  container: PAttachment;
}): JSX.Element {
  return (
    <label>
      {props.container.config.caption}
      {props.container.config.required ? ' *' : ''}
      <input
        type="file"
        onChange={(e) => props.container.uploadFile(e as unknown as Event)}
      />
      {props.container.config.helperText}
      {props.container.config.validatemessages}
    </label>
  );
}

// applications/angular-rabobank/src/pega/container-mapping/Attachment.component.ts
import { Component } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';
import { Attachment } from '@labb/dx-engine';

@Component({
  selector: 'dx-attachment-control',
  template: `
    <label>
      {{ container.config.label }}{{ container.config.required ? ' *' : '' }}
      <input type="file" (change)="uploadFile($event)" />
      {{ container.config.helperText }}
    </label>
  `,
})
export class AttachmentComponent extends PContainerComponent<Attachment> {
  public progress!: ProgressEvent<EventTarget>;
  public error!: boolean | File;

  public async uploadFile(e: Event): Promise<void> {
    await this.container.uploadFile(e);
  }
}
