// applications/vue-hca/src/app/container-mapping/Checkbox.vue
<script setup lang="ts">
import { PContainer } from '@labb/dx-engine';

const props = defineProps<{
    container: PContainer;
}>();

function getValue(
    target: EventTarget | null
): number | Date | boolean | string | null {
    const t: HTMLInputElement = target as HTMLInputElement;
    return t.checked;
}

function change(event: Event) {
    props.container.updateFieldValue(getValue(event.target))
}

function blur(event: Event) {
    props.container.triggerFieldChange(getValue(event.target))
}
</script>

<template>
    <div>
        <label :for="container.id">
            <input type="checkbox"
                :id="container.id"
                :name="container.config.label" 
                :checked="container.config.value"
                :disabled="container.config.readOnly"
                @change="change"
                @blur="blur" />
                {{ props.container.config.caption }}
                {{ container.config.required ? ' *' : '' }}
                <span v-if="container.config.helperText"
                    :data-tooltip="container.config.helperText">?</span>
        </label>
        {{ container.config.helperText }}
        {{ container.config.validatemessage }}
    </div>
</template>

// applications/angular-rabobank/src/pega/container-mapping/Checkbox.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';

@Component({
  selector: 'dx-checkbox',
  template: `
  <dx-checkbox-control
    [label]="container.config.caption" 
    [labelEnd]="container.config.helperText"
    [errorMessage]="container.config.validatemessage"
    [checked]="container.config.value">
      <input
        [id]="container.id"
        type="checkbox"
        [attr.readonly]="container.config.readOnly"
        [value]="container.config.value"
        (change)="container.updateFieldValue(getValue($event.target))"
        (blur)="container.triggerFieldChange(getValue($event.target))"
      />
  </dx-checkbox-control>
   `
})
export class CheckboxComponent extends PContainerComponent {
  public getValue(
    target: EventTarget | null
  ): number | Date | boolean | string | null {
    const t: HTMLInputElement = target as HTMLInputElement;
    return t.checked;
  }
}
