// applications/react-cmcmarkets/src/pega/containers/RadioButtons.tsx
import { PContainer } from '@labb/dx-engine';
import CmCRadio from '../../cmc-design/cmc-radio';

export default function DxRadioButtons(props: { container: PContainer }) {
  return <CmCRadio
      label={props.container.config.label}
      options={props.container.config.datasource}
      value={props.container.config.value}
      helperText={props.container.config.helperText}
      errorMessage={props.container.config.validatemessage}
      selected={key => {
        props.container.updateFieldValue(key);
        props.container.triggerFieldChange(key);
      }}
    />
}

// applications/angular-rabobank/src/pega/container-mapping/RadioButtons.component.ts
import { Component } from '@angular/core';
import { PContainerComponent } from '@labb/angular-adapter';

@Component({
  selector: 'dx-radio-buttons-control',
  template: `
    <dx-input-wrapper
        [errorMessage]="container.config.validatemessage | translate:'radiobuttons'">
        <dx-radio-group
            class="sfc-display-inline-block"
            [hasErrors]="!!container.config.validatemessage"
            [value]="container.config.value"
            [label]="container.config.label"
            [options]="container.config.datasource"
            (valueChanged)="changeAndCommit($event)"></dx-radio-group>
    </dx-input-wrapper>
  `,
})
export class RadioButtonsComponent extends PContainerComponent {
  public changeAndCommit(value: string) {
    this.container.updateFieldValue(value);
    this.container.triggerFieldChange(value);
  }
}
