// applications/vue-reference/src/app/container-mapping/FlowContainer.vue
<script setup lang="ts">
import { ActionButton, Assignment } from '@labb/constellation-core-types';
import { FlowContainer } from '@labb/dx-engine';
import { DxContainer } from '@labb/vue-adapter';
import { ref } from 'vue';

const props = defineProps<{
    container: FlowContainer;
}>();
const todoAssignments = ref();

function click(button: ActionButton) {
    const promise = props.container.buttonClick(button);
    promise.catch(err => handleActionError(err))
}
function handleActionError(e: Error) {
    console.error(e);
    errorMessage.value = e.message || 'Error';
}

function openAssignment(assignment: Assignment) {
    props.container.openAssignment(assignment);
}

function updateAssignments(): void {
    todoAssignments.value = props.container.getTodoAssignments();
}

updateAssignments();
props.container.updates.subscribe(() => {
    updateAssignments();
});

const errorMessage = ref<string | null>(null);
</script>

<template>
    <form>
        <template v-if="!container.hasAssignment()">
            <div v-for="assignment in todoAssignments">
                <div>{{ assignment.processName }} > {{ assignment.name }}</div>
                <div>Assigned to {{ assignment.assigneeInfo?.name }}</div>
                <button type="button" @click="openAssignment(assignment)">Go</button>
            </div>
            <div v-if="todoAssignments.length === 0">
                <h2>Uw gegevens zijn goed ontvangen!</h2>
                <strong>Wij nemen zo spoedig mogelijk contact met u
                    op.</strong>
            </div>

        </template>
        <template v-if="container.hasAssignment()">
            <h2>
                {{ container.getActiveViewLabel() ||
                    container.getAssignmentName() }}
            </h2>
            <nav v-if="container.navigation">
                <ol>
                    <li v-for="step of container.navigation.steps">{{step.name}} [{{step.visited_status}}]</li>
                </ol>
            </nav>

            <fieldset>
                <DxContainer v-for="child in container.children" :key="child.id" :container="child" />
            </fieldset>

            <template v-if="container.actionButtons">
                <button v-for="button in container.actionButtons.secondary" 
                    type="button"
                    :key="button.jsAction" 
                    @click="click(button)">
                    {{ button.name }}
                </button>
                <button v-for="button in container.actionButtons.main"
                    type="button"
                    :key="button.jsAction"
                    @click="click(button)">
                    {{ button.name }}
                </button>
            </template>
        </template>
    </form>
</template>

// applications/angular-rabobank/src/pega/containers/FlowContainer.component.ts
import { Component, OnInit } from '@angular/core';
import { ActionButton, Assignment } from '@labb/constellation-core-types';
import { PContainerComponent } from '@labb/angular-adapter';
import { FlowContainer } from '@labb/dx-engine';

@Component({
  selector: 'dx-flow-container',
  template: `
      @for (message of container.config.caseMessages; track message) {
        <div>
          {{message}}
        </div>
    }
    @if (!container.hasAssignment()) {
          @for(assignment of todoAssignments; track assignment.ID) {
            <div>
              <div>{{assignment.processName}} > {{assignment.name}}</div>
              <div>Assigned to {{assignment.assigneeInfo?.name}}</div>
              <button type="button" (click)="openAssignment(assignment)">Go</button>
            </div>
          }
          @if (todoAssignments.length === 0) {
            <div class="card" appearance="outlined">
              <h2>Uw gegevens zijn goed ontvangen!</h2>
              <strong>Wij nemen zo spoedig mogelijk contact met u op.</strong>
            </div>
          }
    } @else {
        <ng-container *ngIf="container.hasAssignment()">
          <h1 class="sfc-heading-1">
            {{ container.getActiveViewLabel() || container.getAssignmentName() }}
          </h1>
          <div class="sfc-row">
            <ng-template
              *ngFor="let child of container.children"
              dxContainer
              [container]="child"
            ></ng-template>
          </div>
          <div class="sfc-margin-block-start-150" *ngIf="container.actionButtons">
            <dx-button
              *ngFor="let button of container.actionButtons.secondary"
              class="sfc-margin-block-end-75 sfc-display-inline-block sfc-margin-inline-end-50"
              type="secondary"
              [loading]="loading === button"
              (click)="buttonClick(button)"
            >
              {{ button.name | translate}}
            </dx-button>
            <dx-button
              *ngFor="let button of container.actionButtons.main"
              class="sfc-margin-block-end-75 sfc-display-inline-block sfc-margin-inline-end-50"
              type="primary"
              [loading]="loading === button"
              (click)="buttonClick(button)"
            >
              {{ button.name | translate}}
            </dx-button>
          </div>
        </ng-container>
    }
  <div>{{ errorMessage | translate}}</div>
  `,
  styles: [],
  standalone: false
})
export class FlowContainerComponent extends PContainerComponent<FlowContainer> implements OnInit {
  public todoAssignments: Assignment[] = [];
  public errorMessage!: string;
  public loading: ActionButton | null = null;

  public override ngOnInit(): void {
    super.ngOnInit();
    this.updateAssignments();
    this.container.updates.subscribe(() => {
      this.updateAssignments();
    });
  }

  public openAssignment(assignment: Assignment) {
    this.container.openAssignment(assignment);
  }

  private updateAssignments(): void {
    this.todoAssignments = this.container.getTodoAssignments();
  }

  public handleActionError(e: Error) {
    console.error(e);
    this.errorMessage = e.message || 'Error';
  }

  public buttonClick(button: ActionButton) {
    this.errorMessage = '';
    if (this.loading) return;
    this.loading = button;
    const action = this.container.buttonClick(button);
    action.finally(() => {
      this.loading = null;
    })
    action.catch((e) => this.handleActionError(e));
  }
}
