// applications/react-centraalbeheer/src/pega/containers/Location.tsx
import { Location } from "@labb/dx-engine";
import { ChangeEvent, useEffect, useRef, useState } from "react";
import TextInput from "../../design-system/cb-text-input";

export default function DxLocation(props: { container: Location }) {
    const map = useRef(null);
    const [suggestions, setSuggestions] = useState<string[]>([]);
    const [searchValue, setSearchValue] = useState<string>('');
    const { container } = props;

    useEffect(() => {
        (async () => {
            if (map.current) {
                await container.loadMap(map.current);
            }
        })();
    }, [map.current]);

    async function updateSearch(event: ChangeEvent) {
        const value = (event.target as HTMLInputElement)?.value;
        setSearchValue(value)
        setSuggestions(await container.getPlacePredictions(value));
    }

    async function select(event: ChangeEvent) {
        const value = (event.target as HTMLSelectElement).value;
        container.updateFieldValue(value);
        container.triggerFieldChange(value);
    }

    return <>
        <TextInput id={props.container.id} label={props.container.config.label} type={'text'} value={searchValue} onChange={(event) => updateSearch(event)} />
        {suggestions.length > 0 && <TextInput id={props.container.id} label={props.container.config.label} type={'select'} options={suggestions} value={container.config.value} onChange={(event) => select(event)} />}
        {container.config.value && <div ref={map} style={{ height: '25rem' }}></div>}
    </>
}

// applications/angular-rabobank/src/pega/containers/Location.component.ts
import { AfterViewInit, Component, ElementRef, ViewChild } from "@angular/core";
import { FormControl } from "@angular/forms";
import { PContainerComponent } from "@labb/angular-adapter";
import { Location } from "@labb/dx-engine";

@Component({
    selector: 'dx-location',
    template: `
        <label> {{container.config.label}}
            <input type="text" [formControl]="searchControl" (change)="updateSearch($event)">
        </label>
        @if(suggestions.length > 0) {
            <select [formControl]="selectControl" (change)="select($event)">
                <option value selected>Select {{container.config.label}}...</option>
                @for(suggestion of suggestions; track suggestion) {
                    <option [value]="suggestion">{{suggestion}}</option>
                }
             </select>
        }
        <div #map style="height: 25rem"></div>
    `,
    standalone: false
})
export class LocationComponent extends PContainerComponent<Location> implements AfterViewInit {
    @ViewChild('map') map!: ElementRef;
    public searchControl = new FormControl('');
    public selectControl = new FormControl('');
    public suggestions: string[] = [];

    public async ngAfterViewInit(): Promise<void> {
        await this.container.loadMap(this.map.nativeElement);
    }

    public async updateSearch(event: Event) {
        this.suggestions = await this.container.getPlacePredictions((event.target as HTMLInputElement)?.value);
    }

    public async select(event: Event) {
        this.container.updateFieldValue((event.target as HTMLSelectElement).value);
        this.container.triggerFieldChange((event.target as HTMLSelectElement).value);
    }
}
