// applications/vue-hca/src/app/container-mapping/MultiSelect.vue
<script setup lang="ts">
import { Multiselect } from '@labb/dx-engine';

const {container} = defineProps<{
    container: Multiselect;
}>();
function search(event: Event) {
    const value = (event.target as HTMLInputElement).value
    container.onSearchHandler(value);
}
</script>

<template>
    <label>
        {{container.config.label}}
        <input type="text" @blur="search($event)">
    </label>
    <label v-for="item in container.itemsTree" :key="item.id">
        <input type="checkbox" :checked="item.selected" 
            @change="container.toggleItem(item.id!)">{{item.primary}}
    </label>
</template>

// applications/react-lvcyclery/src/pega/containers/MultiSelect.tsx
import { Multiselect } from "@labb/dx-engine";
import { ChangeEvent, useState } from "react";

export default function DxMultiSelect(props: { container: Multiselect }) {
    const [searchValue, setSearchValue] = useState('');
    const { container } = props;

    function search(event: ChangeEvent) {
        const value = (event.target as HTMLInputElement).value;
        setSearchValue(value);
        container.onSearchHandler(value);
    }

    return <>
        <label>
            {container.config.label}
            <input type="text" value={searchValue} onBlur={e => search(e)} />
        </label>
        {container.itemsTree.map(item =>
            <label key={item.id}>
                <input type="checkbox" checked={item.selected} onChange={e => container.toggleItem(item.id!)} />{item.primary}
            </label>
        )}
    </>
}
