// applications/angular-carbon/src/pega/containers/FlowContainer.component.ts
import { Component, OnInit } from '@angular/core';
import { ActionButton, ActionButtons, Assignment } from '@labb/constellation-core-types';
import { PContainerComponent } from '@labb/angular-adapter';
import { FlowContainer } from '@labb/dx-engine';

import { Step } from 'carbon-components-angular';

@Component({
  selector: 'dx-flow-container',
  template: `
    @for (message of container.config.caseMessages; track message) {
      <div>
        {{message}}
      </div>
    }
    @if (!container.hasAssignment()) {
        @for(assignment of todoAssignments; track assignment.ID) {
          <div>
            <div>{{assignment.processName}} > {{assignment.name}}</div>
            <div>Assigned to {{assignment.assigneeInfo?.name}}</div>
            <button type="button" (click)="openAssignment(assignment)">Go</button>
          </div>
        }
    } @else {
      <div ibmRow>
        <div ibmCol [columnNumbers]="leftColumn">
            <ibm-progress-indicator [orientation]="navigationOrientation"
              [steps]="steps" [current]="currentStep"> </ibm-progress-indicator>
        </div>
        <div ibmCol [columnNumbers]="rightColumn">
          <div ibmGrid>
            <div class="cds--stack-vertical cds--stack-scale-4">
              <div ibmRow>
                <h4>{{ title }}</h4>
              </div>
              
              <div ibmRow>
                <ng-template *ngFor="let child of container.children"
                  dxContainer [container]="child"></ng-template>
              </div>

              <div ibmRow *ngIf="buttons">
                <button ibmButton="secondary"
                  *ngFor="let button of buttons.secondary"
                  (click)="buttonClick(button)">
                  {{ button.name }}
                </button>
                <button ibmButton="primary"
                  *ngFor="let button of buttons.main"
                  (click)="buttonClick(button)">
                  {{ button.name }}
                </button>
              </div>
            </div>
            <ibm-toast *ngIf="errorMessage" [notificationObj]="{
                type: 'error',
                title: 'Error',
                subtitle: 'something went wrong',
                caption: errorMessage,
                showClose: true}"></ibm-toast>
          </div> 
        </div>
      </div>
        }
  `,
  standalone: false
})
export class FlowContainerComponent extends PContainerComponent<FlowContainer> implements OnInit {
  public errorMessage!: string;
  public todoAssignments: Assignment[] = [];
  public loading = false;

  public get title(): string {
    return this.container.getActiveViewLabel() || this.container.getAssignmentName();
  }

  public get steps(): Step[] {
    return this.container.navigation?.steps?.map(step => ({
      text: step.name,
      state: [],
      label: step.ID
    })) ?? [];
  }

  public get currentStep(): number {
    return this.container.navigation?.steps?.findIndex(step => step.visited_status === 'current') ?? 0;
  }

  public get navigationOrientation(): 'horizontal' | 'vertical' {
    return this.container.navigation?.template === 'Vertical' ? 'vertical' : 'horizontal';
  }

  public get leftColumn() {
    return this.navigationOrientation === 'vertical' ? {'lg': 2, 'md': 2, 'sm': 2} : {'lg': 10, 'md': 10, 'sm': 10};
  }

  public get rightColumn() {
    return this.navigationOrientation === 'vertical' ? {'lg': 6, 'md': 6, 'sm': 6} : {'lg': 10, 'md': 10, 'sm': 10};
  }

  public get buttons(): ActionButtons {
    return this.container.actionButtons;
  }

  public override ngOnInit(): void {
    super.ngOnInit();
    this.updateAssignments();
    this.container.updates.subscribe(() => {
      this.updateAssignments();
    });
  }

  public openAssignment(assignment: Assignment) {
    this.container.openAssignment(assignment);
  }

  private updateAssignments(): void {
    this.todoAssignments = this.container.getTodoAssignments();
  }

  public buttonClick(button: ActionButton): void {
    try {
      this.container.buttonClick(button)
    } catch (e) {
      this.handleActionError(e as Error);
    }
  }

  public handleActionError(e: Error) {
    console.error(e);
    this.errorMessage = e.message || 'Error';
  }
}

// applications/react-carbon/src/pega/containers/FlowContainer.tsx
import {
  Button, Column, Grid, ProgressIndicator,
  ProgressStep, Row, Stack, Tile,
  ToastNotification
} from '@carbon/react';
import { Assignment } from '@labb/constellation-core-types';
import { FlowContainer } from '@labb/dx-engine';
import { GeneratePContainer } from '@labb/react-adapter';
import { useEffect, useState } from 'react';

export default function DxFlowContainer(props: { container: FlowContainer }) {
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [todoAssignments, setTodoAssignments] = useState<Assignment[]>([]);

  useEffect(() => {
    updateAssignments();
    props.container.updates.subscribe(() => {
      updateAssignments();
    });
  }, []);

  function openAssignment(assignment: Assignment) {
    props.container.openAssignment(assignment);
  }

  function updateAssignments(): void {
    setTodoAssignments(props.container.getTodoAssignments());
  }

  function handleActionError(e: Error) {
    console.error(e);
    setErrorMessage(e.message || 'Error');
  }

  function currentStep(): number {
    return props.container.navigation?.steps?.findIndex(step => step.visited_status === 'current') ?? 0;
  }

  function isVertical(): boolean {
    return props.container.navigation?.template === 'Vertical';
  }

  function colCount(): number {
    return 10
  }

  return <>
    {props.container.config.caseMessages?.map(message =>
      <div key={message}>
        {message}
      </div>
    )}
    {(props.container.config as any).httpMessages?.map((message: any) =>
      message.type === 'error' ? <em key={message.message}>
        {message.message}
      </em> : <div>{message.message}</div>
    )}
    {!props.container.hasAssignment() && <>
      {todoAssignments.map(assignment =>
        <div key={assignment.ID}>
          <div>{assignment.processName} {'>'} {assignment.name}</div>
          <div>Assigned to {assignment.assigneeInfo?.name}</div>
          <Button type="button" onClick={() => openAssignment(assignment)}>Go</Button>
        </div>
      )}
    </>}
    {props.container.hasAssignment() && <Grid>
      <Column sm={isVertical() ? 2 : 4} md={isVertical() ? 2 : 8} lg={isVertical() ? 4 : 16}>
        <ProgressIndicator currentIndex={currentStep()} vertical={isVertical()}>
          {props.container.navigation?.steps.map((step, i) => (
            <ProgressStep
              key={step.ID}
              label={step.name}
            />
          ))}
        </ProgressIndicator>
      </Column>
      <Column sm={isVertical() ? 2 : 4} md={isVertical() ? 6 : 8} lg={isVertical() ? 12 : 16}>
        <Stack gap={4}>
          <Row>
            <h4>
              {props.container.getActiveViewLabel() ||
                props.container.getAssignmentName()}
            </h4>
          </Row>
          <Row>
            {props.container.children.map((child) => (
              <GeneratePContainer key={child.id} container={child} />
            ))}
          </Row>
          {props.container.actionButtons && (
            <Row>
              {props.container.actionButtons.secondary.map((button, idx) => (
                <Button
                  key={`secondary_${idx}`}
                  kind="secondary"
                  onClick={() =>
                    props.container.buttonClick(button).catch(handleActionError)
                  }
                >
                  {button.name}
                </Button>
              ))}
              {props.container.actionButtons.main.map((button, idx) => (
                <Button
                  key={`main_${idx}`}
                  onClick={() =>
                    props.container.buttonClick(button).catch(handleActionError)
                  }
                >
                  {button.name}
                </Button>
              ))}
            </Row>
          )}
        </Stack>
      </Column>
    </Grid>}
    {errorMessage && <ToastNotification
      role="status"
      title="Error"
      timeout={1000}
      caption={errorMessage} />}
  </>
}
